import type {
  ArrayLit,
  AssignExpr,
  BinaryExpr,
  BinaryOp,
  Block,
  CallExpr,
  Child,
  ClassRef,
  Expr,
  ForExpr,
  IfExpr,
  Lambda,
  LocalLet,
  MarkdownBlock,
  MemberExpr,
  MethodCallExpr,
  ObjectLit,
  Program,
  Prop,
  Stmt,
  ExternalLambda,
  StyleBlock,
  TagCall,
  TemplateLit,
  TryExpr,
} from './ast.js'
import { lineColAt } from './diagnostics.js'
import MarkdownIt from 'markdown-it'

// Singleton markdown-it — CommonMark + linkify + typographer. Code-
// block highlighting is **pluggable**: callers (e.g. @tu-lang/tu-shu)
// inject a highlighter via `setMarkdownHighlight` before compiling
// pages, so the same Shiki grammar set drives both the SSG and the
// site that consumes it. Without an injected highlighter, code
// blocks fall back to plain `<pre><code class="language-X">`.
let mdInstance: MarkdownIt | null = null
let mdHighlighter: ((code: string, lang: string) => string) | null = null

/**
 * Install a custom code-block highlighter for `markdown { … }` body
 * rendering. The function receives raw code text + the fence's `lang`
 * tag (e.g. `'tu'`, `'ts'`), and must return a complete HTML string
 * (typically `<pre class="shiki…"><code>…</code></pre>`). Throwing or
 * returning empty string falls back to markdown-it's default.
 *
 * Calling this resets the singleton markdown-it instance so the new
 * highlighter applies on the next compile.
 */
export function setMarkdownHighlight(
  fn: ((code: string, lang: string) => string) | null
): void {
  mdHighlighter = fn
  mdInstance = null
}

function getMd(): MarkdownIt {
  if (!mdInstance) {
    const opts: ConstructorParameters<typeof MarkdownIt>[0] = {
      html: true,
      linkify: true,
      typographer: true,
    }
    if (mdHighlighter) {
      const hi = mdHighlighter
      opts.highlight = (code, lang) => {
        try {
          return hi(code, lang) ?? ''
        } catch {
          return ''
        }
      }
    }
    mdInstance = new MarkdownIt(opts)
  }
  return mdInstance
}

/**
 * Auto-injected import at the head of every compiled module.
 *
 * In TS-emit mode we ALSO bring in the type-only exports `Child` and
 * `VNode` so user annotations like `(children: VNode[])` or
 * `(items: Child[])` resolve without requiring the user to write the
 * import themselves. JS-emit drops the type-only members (they're not
 * legal ESM at runtime).
 */
function runtimeImportLine(tsMode: boolean): string {
  if (tsMode) return `import { h, Signal, type Child, type VNode } from '@tu-lang/runtime'`
  return `import { h, Signal } from '@tu-lang/runtime'`
}

export interface SourceMapV3 {
  version: 3
  file?: string
  sources: string[]
  sourcesContent: string[]
  names: string[]
  mappings: string
}

/**
 * A finer-grained mapping than `StmtMapping`: ties a span of generated bytes
 * to a span of source bytes. Codegen records one of these per emitted leaf
 * token (identifiers, literals, etc.) so the LSP can squiggle the offending
 * token instead of the whole `let` header.
 *
 * Spans are byte ranges; `srcEnd` is exclusive. The LSP's diagnostic-range
 * mapping consumes this list directly (it doesn't go through V3 VLQ encoding,
 * since V3 segments don't carry an explicit source-end).
 */
export interface TokenMapping {
  /** Byte offset of the span's first character in the generated code. */
  jsStart: number
  /** Byte offset after the span's last character in the generated code. */
  jsEnd: number
  /** Byte offset of the span's first character in the `.tu` source. */
  srcStart: number
  /** Byte offset after the span's last character in the `.tu` source. */
  srcEnd: number
}

/**
 * Top-level binding kinds — drives whether an identifier read becomes
 * `name.get()` or stays as a plain reference.
 */
export type CellKind = 'state' | 'computed' | 'function'

/** Tu `==` / `!=` map to JS strict equality to avoid coercion surprises.
 *  Other operators (logical, nullish, arithmetic, relational) pass
 *  through verbatim — they have identical semantics in JS. */
const BINARY_OP_JS: Record<BinaryOp, string> = {
  '+': '+', '-': '-', '*': '*', '/': '/', '%': '%',
  '==': '===', '!=': '!==',
  '<': '<', '<=': '<=', '>': '>', '>=': '>=',
  '||': '||', '&&': '&&', '??': '??',
}

/** Per-component scoping state. Populated for any top-level `let X = (…) => { … }`
 * whose body contains at least one ClassRef. The hash is the suffix appended
 * to every declared class name in both markup and style block, so the markup
 * `.foo` reference resolves to the same hashed string as the style block's
 * `.foo` selector. */
interface ScopeCtx {
  hash: string
  declared: Set<string>
}

interface StmtMapping {
  /** Byte offset of the statement's first character in the generated JS. */
  jsOffset: number
  /** Byte offset of the statement's `let` keyword in the source. */
  srcOffset: number
}

interface BuildResult {
  code: string
  stmtMappings: StmtMapping[]
  tokenMappings: TokenMapping[]
}

/**
 * Per-emit options that the rest of the toolchain (LSP, CLI, vite plugin)
 * uses to give codegen extra context it can't derive from a single source
 * file.
 */
export interface CodegenOptions {
  /**
   * Per-imported-name classification. The compiler defaults to `'function'`
   * for any name brought in by `import { X } from "./M.tu"` because, looking
   * at the importing source alone, it can't tell what kind `X` was declared
   * as in the exporting module. Callers who DO know (the LSP's shadow graph,
   * the CLI's BFS, the vite plugin's resolver) pass the map here so reads of
   * imported state / computed cells emit `X.get()` instead of `X` — fixing
   * the M2.1 reactivity bug.
   */
  importedNameKinds?: ReadonlyMap<string, CellKind>
}

function buildBody(program: Program, tsMode: boolean, opts?: CodegenOptions): BuildResult {
  const cells = analyzeProgram(program, opts?.importedNameKinds)
  const scopes = analyzeScopedComponents(program)
  // Collect every top-level type-alias name so the Codegen can skip the
  // auto-`${Name}Props` interface emit when the user has hand-written a
  // type alias of the same name (which would otherwise collide with TS
  // diagnostic "Duplicate identifier 'XProps'"). Type aliases are
  // erased in JS mode but the dedup is cheap to compute either way.
  const declaredTypeNames = new Set<string>()
  for (const stmt of program.body) {
    if (stmt.kind === 'TypeAlias') declaredTypeNames.add(stmt.name)
  }
  const cg = new Codegen(cells, scopes, tsMode, declaredTypeNames)
  cg.write(`${runtimeImportLine(tsMode)}\n\n`)
  for (const stmt of program.body) {
    // Type aliases erase entirely in JS mode — they have no runtime presence.
    if (stmt.kind === 'TypeAlias' && !tsMode) continue
    cg.recordStmtMapping(stmt.start)
    cg.emitStmt(stmt)
    cg.write('\n')
  }
  return cg.finish()
}

export function generate(program: Program, opts?: CodegenOptions): string {
  return buildBody(program, false, opts).code
}

/**
 * Generate JS with a V3 source map. The returned code carries an inline
 * `//# sourceMappingURL=` data-URL footer; the same map is also returned
 * separately for tooling that consumes it programmatically. The richer
 * per-token mapping list is exposed alongside for the LSP / type-checker.
 */
export function generateWithMap(
  program: Program,
  source: string,
  filename?: string,
  opts?: CodegenOptions
): { code: string; map: SourceMapV3; tokenMappings: TokenMapping[] } {
  const result = buildBody(program, false, opts)
  const sourceName = filename ?? 'input.tu'
  const map = buildV3Map(result.stmtMappings, result.tokenMappings, result.code, source, sourceName)
  const inline = base64Encode(JSON.stringify(map))
  const footer = `//# sourceMappingURL=data:application/json;charset=utf-8;base64,${inline}\n`
  return { code: result.code + footer, map, tokenMappings: result.tokenMappings }
}

/**
 * Generate TypeScript source with a V3 source map. Same semantics as
 * `generateWithMap` but lambda parameter type annotations from the Tu source
 * are preserved (`(name: string)` instead of `(name)`), so tsserver can infer
 * the rest.
 */
export function generateTSWithMap(
  program: Program,
  source: string,
  filename?: string,
  opts?: CodegenOptions
): { code: string; map: SourceMapV3; tokenMappings: TokenMapping[] } {
  const result = buildBody(program, true, opts)
  const sourceName = filename ?? 'input.tu'
  const map = buildV3Map(result.stmtMappings, result.tokenMappings, result.code, source, sourceName)
  const inline = base64Encode(JSON.stringify(map))
  const footer = `//# sourceMappingURL=data:application/json;charset=utf-8;base64,${inline}\n`
  return { code: result.code + footer, map, tokenMappings: result.tokenMappings }
}

function analyzeProgram(
  program: Program,
  importedNameKinds?: ReadonlyMap<string, CellKind>
): Map<string, CellKind> {
  const cells = new Map<string, CellKind>()
  for (const stmt of program.body) {
    if (stmt.kind === 'LetDecl') {
      cells.set(stmt.name, classifyValue(stmt.value))
    }
    // Imported names: prefer the caller-provided kind (state / computed /
    // function); otherwise default to 'function' for the standalone-compile
    // path that has no graph view.
    if (stmt.kind === 'ImportDecl') {
      for (const name of stmt.names) {
        cells.set(name, importedNameKinds?.get(name) ?? 'function')
      }
    }
  }
  return cells
}

/** Public re-export so callers (LSP, CLI) can build the importedNameKinds map. */
export function classifyTopLevel(value: Expr): CellKind {
  return classifyValue(value)
}

/**
 * Empty-array literal at the cell-init site? Used by codegen to widen
 * `Signal.State` / `Signal.Computed` to `<unknown[]>` so a later assign
 * of a real array isn't blocked by tsserver's `never[]` inference of the
 * literal.
 */
function isEmptyArray(expr: Expr | undefined): boolean {
  return expr?.kind === 'ArrayLit' && expr.elements.length === 0
}

function classifyValue(expr: Expr): CellKind {
  if (expr.kind === 'Lambda') return 'function'
  if (expr.kind === 'ExternalLambda') return 'function'
  if (expr.kind === 'CallExpr' && expr.callee === 'computed') return 'computed'
  return 'state'
}

/**
 * Public — for the LSP's ClassRef completion. Returns a map from
 * component name to the set of class names declared in that component's
 * `style { … }` block. Mirrors the internal `analyzeScopedComponents`
 * but drops the per-component hash (which IDE consumers don't need).
 */
export function getScopedClassMap(program: Program): Map<string, Set<string>> {
  const out = new Map<string, Set<string>>()
  for (const [name, ctx] of analyzeScopedComponents(program)) {
    out.set(name, ctx.declared)
  }
  return out
}

function analyzeScopedComponents(program: Program): Map<string, ScopeCtx> {
  const out = new Map<string, ScopeCtx>()
  for (const stmt of program.body) {
    if (stmt.kind !== 'LetDecl') continue
    if (stmt.value.kind !== 'Lambda') continue
    const refs = new Set<string>()
    collectClassRefs(stmt.value.body, refs)
    if (refs.size === 0) continue
    const styleBodies: string[] = []
    collectStyleBlockBodies(stmt.value.body, styleBodies)
    const declared = new Set<string>()
    for (const css of styleBodies) {
      for (const c of findCssClasses(css)) declared.add(c)
    }
    const hash = fnv1a6(`${stmt.name} ${styleBodies.join(' ')}`)
    out.set(stmt.name, { hash, declared })
  }
  return out
}

class Codegen {
  /** Stack of binding-name sets shadowing top-level cells (innermost last). */
  private readonly shadowed: Set<string>[] = []
  /** Stack of scoped-component contexts pushed at LetDecl emit time. */
  private readonly scopes: ScopeCtx[] = []
  /** Streaming output buffer. */
  private buffer = ''
  /** Per-statement mapping anchors (one per top-level statement). */
  private readonly stmtMappings: StmtMapping[] = []
  /** Per-token mapping spans (one per emitted leaf-ish source span). */
  private readonly tokenMappings: TokenMapping[] = []

  constructor(
    private readonly cells: Map<string, CellKind>,
    private readonly scopedComponents: Map<string, ScopeCtx>,
    private readonly tsMode: boolean = false,
    private readonly declaredTypeNames: ReadonlySet<string> = new Set()
  ) {}

  write(text: string): void {
    this.buffer += text
  }

  recordStmtMapping(srcOffset: number): void {
    this.stmtMappings.push({ jsOffset: this.buffer.length, srcOffset })
  }

  /**
   * Run `fn` and record a TokenMapping spanning the byte range `fn` writes
   * into the buffer. The mapping ties that generated span back to
   * `[srcStart, srcEnd)` in the `.tu` source.
   */
  private mark(srcStart: number, srcEnd: number, fn: () => void): void {
    const jsStart = this.buffer.length
    fn()
    const jsEnd = this.buffer.length
    if (jsEnd > jsStart) {
      this.tokenMappings.push({ jsStart, jsEnd, srcStart, srcEnd })
    }
  }

  finish(): BuildResult {
    return {
      code: this.buffer,
      stmtMappings: this.stmtMappings,
      tokenMappings: this.tokenMappings,
    }
  }

  emitStmt(stmt: Stmt): void {
    if (stmt.kind === 'ImportDecl') {
      const src = this.rewriteSource(stmt.source)
      const parts: string[] = []
      if (stmt.default !== undefined) parts.push(stmt.default)
      if (stmt.namespace !== undefined) parts.push(`* as ${stmt.namespace}`)
      if (stmt.names.length > 0) parts.push(`{ ${stmt.names.join(', ')} }`)
      this.write(`import ${parts.join(', ')} from ${JSON.stringify(src)}`)
      return
    }
    if (stmt.kind === 'ReExportDecl') {
      const src = this.rewriteSource(stmt.source)
      this.write(`export { ${stmt.names.join(', ')} } from ${JSON.stringify(src)}`)
      return
    }
    if (stmt.kind === 'TypeAlias') {
      // Only reached in TS mode; buildBody skips this stmt in JS mode.
      const prefix = stmt.exported ? 'export type' : 'type'
      this.write(`${prefix} `)
      this.mark(stmt.nameStart, stmt.nameEnd, () => this.write(stmt.name))
      this.write(' = ')
      this.mark(stmt.typeStart, stmt.typeEnd, () => this.write(stmt.type))
      return
    }
    const decl = stmt
    const prefix = decl.exported ? 'export const' : 'const'
    const kind = this.cells.get(decl.name) ?? 'state'
    const ctx = this.scopedComponents.get(decl.name)
    if (ctx) this.scopes.push(ctx)
    try {
      // M3.9: for an exported lambda with all-typed params, emit a named
      // `${Name}Props` interface BEFORE the const so downstream consumers
      // (TS code reading the .d.ts) get a reusable shape. Lambdas with any
      // untyped param are skipped — we don't want to invent `unknown` fields.
      // If the user has hand-declared a `${Name}Props` type alias in this
      // module, skip the auto-emit to avoid TS "Duplicate identifier" — the
      // hand-written shape always wins.
      if (
        this.tsMode &&
        decl.exported &&
        decl.value.kind === 'Lambda' &&
        decl.value.params.length >= 1 &&
        decl.value.params.every((p) => p.type !== undefined) &&
        !this.declaredTypeNames.has(`${decl.name}Props`)
      ) {
        this.write(`export interface ${decl.name}Props { `)
        for (let i = 0; i < decl.value.params.length; i++) {
          if (i > 0) this.write('; ')
          const p = decl.value.params[i]!
          this.mark(p.nameStart, p.nameEnd, () => this.write(p.name))
          this.write(`: ${p.type}`)
        }
        this.write(' }\n')
      }
      this.write(`${prefix} `)
      // Mark the bound name so a TS error on `count` lands on the source `count`.
      this.mark(decl.nameStart, decl.nameEnd, () => this.write(decl.name))
      // Emit a TS type annotation when the user supplied one.
      //
      // Default behavior: lambdas pass through as-is; state / computed cells
      // get the declared type wrapped in their Signal box so the variable's
      // actual type matches the wrapped value (M2.2 ergonomic).
      //
      // Escape hatch: if the user's annotation ALREADY starts with
      // `Signal.State<` / `Signal.Computed<`, we trust them and skip the
      // double-wrap — useful when they want to declare an explicit Signal
      // shape (e.g. `let cell: Signal.State<MyShape> = …`).
      if (this.tsMode && decl.type !== undefined) {
        const t = decl.type.trim()
        const preWrapped =
          t.startsWith('Signal.State<') || t.startsWith('Signal.Computed<')
        if (preWrapped || kind === 'function') {
          this.write(`: ${decl.type}`)
        } else if (kind === 'computed') {
          this.write(`: Signal.Computed<${decl.type}>`)
        } else {
          this.write(`: Signal.State<${decl.type}>`)
        }
      }
      this.write(' = ')
      if (kind === 'function') {
        this.emitExpr(decl.value)
        return
      }
      if (kind === 'computed') {
        const v = decl.value as CallExpr
        const arg = v.args[0]
        // Widen empty `computed([])` to `Signal.Computed<any[]>` so
        // assignments / reads / iteration aren't blocked by tsserver's
        // `never[]` inference. `any[]` (vs `unknown[]`) keeps `for item in`
        // ergonomic — users wanting tighter types should annotate.
        const wrapper =
          this.tsMode && decl.type === undefined && isEmptyArray(arg)
            ? 'new Signal.Computed<any[]>(() => '
            : 'new Signal.Computed(() => '
        this.write(wrapper)
        if (arg) {
          // Same arrow-body ambiguity guard as emitLambda: `() => { … }` reads
          // as a block, not an object literal — paren-wrap to disambiguate.
          if (arg.kind === 'ObjectLit') {
            this.write('(')
            this.emitExpr(arg)
            this.write(')')
          } else {
            this.emitExpr(arg)
          }
        } else this.write('undefined')
        this.write(')')
        return
      }
      // state
      const widenEmpty =
        this.tsMode && decl.type === undefined && isEmptyArray(decl.value)
      this.write(widenEmpty ? 'new Signal.State<any[]>(' : 'new Signal.State(')
      this.emitExpr(decl.value)
      this.write(')')
    } finally {
      if (ctx) this.scopes.pop()
    }
  }

  /**
   * In TS-emit mode, rewrite a `./foo.tu` import source to `./foo.ts` so
   * tsserver resolves the sibling shadow file. Other extensions and
   * non-relative paths pass through unchanged.
   */
  private rewriteSource(source: string): string {
    if (this.tsMode && source.endsWith('.tu')) {
      return source.slice(0, -'.tu'.length) + '.ts'
    }
    return source
  }

  emitExpr(expr: Expr): void {
    switch (expr.kind) {
      case 'Lambda':
        this.emitLambda(expr)
        return
      case 'TagCall':
        this.emitTagCall(expr)
        return
      case 'CallExpr':
        this.emitCallExpr(expr)
        return
      case 'BinaryExpr':
        this.emitBinaryExpr(expr)
        return
      case 'StringLit':
        this.mark(expr.start, expr.end, () => this.write(JSON.stringify(expr.value)))
        return
      case 'NumberLit':
        this.mark(expr.start, expr.end, () => this.write(String(expr.value)))
        return
      case 'Ident':
        this.emitIdentRead(expr.name, expr.start, expr.end)
        return
      case 'Block':
        this.emitBlock(expr)
        return
      case 'IfExpr':
        this.emitIfExpr(expr)
        return
      case 'ForExpr':
        this.emitForExpr(expr)
        return
      case 'StyleBlock':
        this.emitStyleBlock(expr)
        return
      case 'MarkdownBlock':
        this.emitMarkdownBlock(expr)
        return
      case 'AssignExpr':
        this.emitAssignExpr(expr)
        return
      case 'MemberAssignExpr':
        this.write('(')
        this.emitExpr(expr.target)
        this.write(' = ')
        this.emitExpr(expr.value)
        this.write(')')
        return
      case 'InvokeExpr':
        this.emitExpr(expr.callee)
        this.write('(')
        for (let i = 0; i < expr.args.length; i++) {
          if (i > 0) this.write(', ')
          this.emitExpr(expr.args[i]!)
        }
        this.write(')')
        return
      case 'RegexLit':
        this.mark(expr.start, expr.end, () => this.write(expr.text))
        return
      case 'ClassRef':
        this.emitClassRef(expr)
        return
      case 'ArrayLit':
        this.emitArrayLit(expr)
        return
      case 'ObjectLit':
        this.emitObjectLit(expr)
        return
      case 'MemberExpr':
        this.emitMemberExpr(expr)
        return
      case 'MethodCallExpr':
        this.emitMethodCallExpr(expr)
        return
      case 'IndexExpr':
        this.emitExpr(expr.object)
        this.write(expr.optional ? '?.[' : '[')
        this.emitExpr(expr.index)
        this.write(']')
        return
      case 'UnaryExpr':
        // Wrap in parens so the result composes safely inside larger
        // expressions (e.g. `a + !b` or `a - -b` read correctly without
        // relying on consumer precedence).
        this.write(`(${expr.op}`)
        this.emitExpr(expr.arg)
        this.write(')')
        return
      case 'NonNullAssertExpr':
        // TS-only: emit `expr!` so tsserver sees the narrowing. In JS-emit
        // mode (default for build / runtime) the assertion is erased —
        // it has no JS semantics. We DON'T just pass through to emitExpr
        // because at runtime `(x)!` would parse as `x!=undefined` lookup
        // ambiguity in some contexts; keep it strictly TS.
        if (this.tsMode) {
          this.emitExpr(expr.arg)
          this.write('!')
        } else {
          this.emitExpr(expr.arg)
        }
        return
      case 'ThrowExpr':
        // Expression position: wrap in IIFE so the throw can sit
        // anywhere a value is expected. Block context emits a clean
        // `throw …;` directly via `emitBlockStmt`.
        this.write('((() => { throw ')
        this.emitExpr(expr.arg)
        this.write('; })())')
        return
      case 'ReturnExpr':
        // Same IIFE trick as ThrowExpr — `return` inside an IIFE just
        // exits that IIFE (the value still escapes via the outer eval).
        // Block context (the common case) bypasses this branch.
        this.write('((() => { return')
        if (expr.value !== undefined) {
          this.write(' ')
          this.emitExpr(expr.value)
        }
        this.write('; })())')
        return
      case 'TryExpr':
        this.emitTryExpr(expr)
        return
      case 'TernaryExpr':
        this.write('(')
        this.emitExpr(expr.cond)
        this.write(' ? ')
        this.emitExpr(expr.then)
        this.write(' : ')
        this.emitExpr(expr.else)
        this.write(')')
        return
      case 'NewExpr':
        this.write('(new ')
        this.emitExpr(expr.arg)
        this.write(')')
        return
      case 'UpdateExpr':
        // Emit the JS-native form so the result value behaves like JS
        // (prefix returns the new value; postfix returns the old). We
        // bypass Tu's .get()/.set() injection here by emitting the
        // operand directly — the operand is gated to ident / member
        // access by parsePostfix, so JS's update semantics apply.
        if (expr.prefix) {
          this.write(`(${expr.op}`)
          this.emitUpdateOperand(expr.arg)
          this.write(')')
        } else {
          this.write('(')
          this.emitUpdateOperand(expr.arg)
          this.write(`${expr.op})`)
        }
        return
      case 'TemplateLit':
        this.emitTemplateLit(expr)
        return
      case 'SpreadElement':
        this.write('...')
        this.emitExpr(expr.arg)
        return
      case 'AwaitExpr':
        this.write('(await ')
        this.emitExpr(expr.arg)
        this.write(')')
        return
      case 'ImportExpr':
        this.write('import(')
        this.emitExpr(expr.arg)
        this.write(')')
        return
      case 'ExternalLambda':
        this.emitExternalLambda(expr)
        return
    }
  }

  private emitExternalLambda(node: ExternalLambda): void {
    if (node.lang !== 'JS') {
      throw new Error(`external ${node.lang} blocks are not yet supported (only \`external JS\`)`)
    }
    if (node.async) this.write('async ')
    this.write('(')
    for (let i = 0; i < node.params.length; i++) {
      if (i > 0) this.write(', ')
      const p = node.params[i]!
      this.mark(p.nameStart, p.nameEnd, () => this.write(p.name))
      if (this.tsMode && p.type !== undefined) {
        this.write(`: ${p.type}`)
      }
    }
    this.write(')')
    if (this.tsMode && node.returnType !== undefined) {
      this.write(`: ${node.returnType}`)
    }
    this.write(' => {')
    // Paste the raw body verbatim. The `mark` call ties the entire
    // emitted region back to the source body span so a TS error inside
    // the pasted JS still squiggles in the .tu file at the right place.
    this.mark(node.bodyStart, node.bodyEnd, () => this.write(node.body))
    this.write('}')
  }

  /** Inside an `UpdateExpr` we want to bypass cell `.get()` injection
   *  on the target — `++count` should emit `++count`, not `++count.get()`.
   *  Recurse manually for ident / member / index access. */
  private emitUpdateOperand(node: Expr): void {
    if (node.kind === 'Ident') {
      this.mark(node.start, node.end, () => this.write(node.name))
      return
    }
    // Member / index access already emits their object via emitExpr —
    // that path injects .get() on cell idents nested inside, which is
    // what we want (the *target* of the increment is the leaf
    // property, not the cell itself).
    this.emitExpr(node)
  }

  private emitTemplateLit(node: TemplateLit): void {
    this.write('`')
    for (let i = 0; i < node.quasis.length; i++) {
      this.write(escapeTemplateChunk(node.quasis[i]!))
      if (i < node.expressions.length) {
        this.write('${')
        this.emitExpr(node.expressions[i]!)
        this.write('}')
      }
    }
    this.write('`')
  }

  private emitTryExpr(node: TryExpr): void {
    // Wrap in an IIFE so the entire try yields a value. Each branch's
    // last expression becomes a `return` so the IIFE produces it.
    this.write('(() => {\n')
    this.emitTryStmt(node, /*allowReturn*/ true)
    this.write('\n})()')
  }

  /** Emit just the `try { … } catch { … } finally { … }` shape, without
   *  the IIFE wrap. Used by emitTryExpr (with wrap) and by
   *  emitBlockTrailingExpr / emitBlockStmt (no wrap — direct
   *  statement). The latter avoids the redundant IIFE on the common
   *  case where try is at a trailing or stmt position inside a block,
   *  AND it sidesteps the async-IIFE problem (an embedded `await`
   *  inside the try body would be a syntax error in a sync IIFE). */
  private emitTryStmt(node: TryExpr, allowReturn: boolean): void {
    this.write('try ')
    this.emitBlockStatementBody(node.body, allowReturn)
    if (node.catchClause) {
      const c = node.catchClause
      if (c.param) {
        this.write(' catch (')
        this.mark(c.paramStart, c.paramEnd, () => this.write(c.param))
        if (this.tsMode && c.type) this.write(`: ${c.type}`)
        this.write(') ')
      } else {
        this.write(' catch ')
      }
      this.emitBlockStatementBody(c.body, allowReturn)
    }
    if (node.finallyClause) {
      this.write(' finally ')
      // Finally body's value is discarded — emit as plain block, no return.
      this.emitBlockStatementBody(node.finallyClause, /*allowReturn*/ false)
    }
  }

  /** Emit a Tu Block as a JS `{ … }` body. When `allowReturn` is true
   *  the last expression becomes `return …;` so the value escapes the
   *  enclosing IIFE; otherwise it's emitted as a plain expression
   *  statement. Used by emitTryExpr. */
  private emitBlockStatementBody(node: Block, allowReturn: boolean): void {
    this.write('{\n')
    let lastExprIdx = -1
    if (allowReturn) {
      for (let i = node.body.length - 1; i >= 0; i--) {
        if (node.body[i]!.kind !== 'LocalLet') {
          lastExprIdx = i
          break
        }
      }
    }
    for (let i = 0; i < node.body.length; i++) {
      const item = node.body[i]!
      this.write('  ')
      if (item.kind === 'LocalLet') {
        this.emitLocalLet(item as LocalLet)
        this.write(';\n')
      } else if (i === lastExprIdx) {
        this.emitBlockTrailingExpr(item as Expr)
      } else {
        this.emitBlockStmt(item as Expr)
      }
    }
    this.write('}')
  }

  /** Emit an item that appears in the trailing (return-position) slot
   *  of a Block. Recognizes the four Tu nodes that *are* JS statements
   *  (Throw / Return / Try) and emits them cleanly without an IIFE
   *  wrap; everything else gets the usual `return …;` prefix. */
  private emitBlockTrailingExpr(item: Expr): void {
    if (item.kind === 'ThrowExpr') {
      this.write('throw ')
      this.emitExpr(item.arg)
      this.write(';\n')
      return
    }
    if (item.kind === 'ReturnExpr') {
      this.write('return')
      if (item.value !== undefined) {
        this.write(' ')
        this.emitExpr(item.value)
      }
      this.write(';\n')
      return
    }
    if (item.kind === 'TryExpr') {
      // Direct try-statement form. Each arm's trailing expr becomes
      // `return …;` so the value escapes via the enclosing block's
      // own return. Avoids the IIFE that emitTryExpr would otherwise
      // emit, which has two benefits: smaller output AND lets `await`
      // inside the body work in async contexts (a sync IIFE would
      // wrap the await and turn it into a syntax error).
      this.emitTryStmt(item, /*allowReturn*/ true)
      this.write('\n')
      return
    }
    this.write('return ')
    this.emitExpr(item)
    this.write(';\n')
  }

  /** Emit a Block item that's NOT in trailing position — its value is
   *  discarded, but Throw / Return / Try / If are still recognized as
   *  statements so they don't pay the IIFE-wrap cost. The `if` case is
   *  load-bearing for early-return patterns: `if (x < 0) { return 0 }`
   *  in source must lower to `if (...) { return 0; }` so the return
   *  exits the *outer* lambda, not just the if's IIFE. */
  private emitBlockStmt(item: Expr): void {
    if (item.kind === 'ThrowExpr') {
      this.write('throw ')
      this.emitExpr(item.arg)
      this.write(';\n')
      return
    }
    if (item.kind === 'ReturnExpr') {
      this.write('return')
      if (item.value !== undefined) {
        this.write(' ')
        this.emitExpr(item.value)
      }
      this.write(';\n')
      return
    }
    if (item.kind === 'IfExpr') {
      this.emitIfStatement(item)
      return
    }
    if (item.kind === 'TryExpr') {
      // Statement-position try doesn't need a return value; emit each
      // arm with allowReturn=false so the value is just discarded.
      this.emitTryStmt(item, /*allowReturn*/ false)
      this.write('\n')
      return
    }
    this.emitExpr(item)
    this.write(';\n')
  }

  /** Emit an IfExpr as a JS `if (…) { … } else { … }` statement so
   *  inner `throw` / `return` reach the surrounding scope. The block
   *  bodies recurse through `emitBlockStatementBody` with
   *  `allowReturn: false` since the parent context already discards
   *  the value. */
  private emitIfStatement(node: IfExpr): void {
    this.write('if (')
    this.emitExpr(node.cond)
    this.write(') ')
    this.emitBlockStatementBody(node.then, /*allowReturn*/ false)
    if (node.else !== undefined) {
      this.write(' else ')
      if (node.else.kind === 'IfExpr') {
        this.emitIfStatement(node.else)
        return
      }
      this.emitBlockStatementBody(node.else, /*allowReturn*/ false)
    }
    this.write('\n')
  }

  private emitMemberExpr(node: MemberExpr): void {
    // Recurse into the object first — if it's a cell ident, this emits the
    // `.get()` injection automatically. Then append the property name as a
    // plain JS dot-access. The property is always a static identifier
    // (parser guarantees `Ident` after the postfix dot).
    this.emitExpr(node.object)
    this.write(node.optional ? '?.' : '.')
    this.mark(node.propertyStart, node.propertyEnd, () => this.write(node.property))
  }

  private emitMethodCallExpr(node: MethodCallExpr): void {
    this.emitExpr(node.object)
    // Empty property + optional flag = optional direct call (`fn?.()`).
    // The parser uses MethodCallExpr-with-empty-property for this shape
    // since its layout (object + args + propertyStart anchor) already
    // covers what we need to emit.
    if (node.optional && node.property === '') {
      this.write('?.(')
    } else {
      this.write(node.optional ? '?.' : '.')
      this.mark(node.propertyStart, node.propertyEnd, () => this.write(node.property))
      this.write('(')
    }
    for (let i = 0; i < node.args.length; i++) {
      if (i > 0) this.write(', ')
      this.emitExpr(node.args[i]!)
    }
    this.write(')')
  }

  private emitArrayLit(node: ArrayLit): void {
    this.write('[')
    for (let i = 0; i < node.elements.length; i++) {
      if (i > 0) this.write(', ')
      this.emitExpr(node.elements[i]!)
    }
    this.write(']')
  }

  private emitObjectLit(node: ObjectLit): void {
    if (node.properties.length === 0) {
      this.write('{}')
      return
    }
    this.write('{ ')
    for (let i = 0; i < node.properties.length; i++) {
      if (i > 0) this.write(', ')
      const p = node.properties[i]!
      if (p.kind === 'ObjectSpread') {
        this.write('...')
        this.emitExpr(p.arg)
        continue
      }
      // Quote string keys (and ident keys that aren't valid JS identifiers,
      // though the parser only accepts valid Ident tokens for the ident case
      // so we trust those). Mark the key span so cross-language navigation
      // lands on the source key.
      const emitted = p.keyKind === 'string' ? JSON.stringify(p.key) : p.key
      this.mark(p.keyStart, p.keyEnd, () => this.write(emitted))
      this.write(': ')
      this.emitExpr(p.value)
    }
    this.write(' }')
  }

  private emitLambda(node: Lambda): void {
    const paramNames = node.params.map((p) => p.name)
    this.shadowed.push(new Set(paramNames))
    try {
      if (node.async) this.write('async ')
      this.write('(')
      for (let i = 0; i < node.params.length; i++) {
        if (i > 0) this.write(', ')
        const p = node.params[i]!
        // Mark the param name so a TS error on the param identifier maps
        // back to its source position.
        this.mark(p.nameStart, p.nameEnd, () => this.write(p.name))
        // In TS mode, preserve `: type` annotations from the Tu source so
        // tsserver can drive IDE features and `.d.ts` generation. In JS mode
        // (default), the names alone are emitted; types are erased.
        if (this.tsMode && p.type !== undefined) {
          this.write(`: ${p.type}`)
        }
      }
      this.write(')')
      if (this.tsMode && node.returnType !== undefined) {
        this.write(`: ${node.returnType}`)
      }
      this.write(' => ')
      // An object literal directly after `=>` is grammatically ambiguous
      // with a function-body block in JS — wrap it in parens so the parser
      // sees an expression, not a labeled-statement block.
      if (node.body.kind === 'ObjectLit') {
        this.write('(')
        this.emitExpr(node.body)
        this.write(')')
      } else if (
        node.body.kind === 'Block' &&
        (node.async || this.lambdaBodyNeedsStmtForm(node.body))
      ) {
        // Block contains return/throw — emit as statement-bodied lambda
        // so those control-flow operators escape the *outer* lambda
        // rather than just the IIFE wrapper of an expression-bodied
        // block. Trailing expression auto-becomes `return …;` so the
        // return value is preserved.
        //
        // async lambdas with a Block body ALWAYS need statement form —
        // otherwise the IIFE wrapper around the block isn't async, and
        // a top-level `await` inside the block becomes a syntax error.
        this.emitLambdaStmtBody(node.body)
      } else if (node.async) {
        // async lambda with a non-Block body — wrap into a synthetic
        // single-item block and emit as statement-bodied. emitBlock-
        // TrailingExpr will recognize TryExpr / ThrowExpr / ReturnExpr
        // and emit them as clean JS statements (no inner IIFE), so an
        // embedded `await` doesn't end up inside a sync wrapper.
        const synth: Block = {
          kind: 'Block',
          body: [node.body],
          start: node.body.start,
          end: node.body.end,
        }
        this.emitLambdaStmtBody(synth)
      } else {
        this.emitExpr(node.body)
      }
    } finally {
      this.shadowed.pop()
    }
  }

  /** Block contains a control-flow operator that must reach the outer
   *  lambda (return / throw, possibly nested in an if's branch). When
   *  this is true, emitLambda picks the statement-bodied form; when
   *  false the cleaner expression-bodied form is fine. */
  private lambdaBodyNeedsStmtForm(node: Block): boolean {
    for (const item of node.body) {
      if (item.kind === 'LocalLet') continue
      if (containsControlFlow(item as Expr)) return true
    }
    return false
  }

  private emitLambdaStmtBody(node: Block): void {
    // Reuse emitBlockStatementBody — same shape, allowReturn so the
    // trailing expression escapes via `return`.
    const localNames = new Set<string>()
    for (const item of node.body) {
      if (item.kind === 'LocalLet') localNames.add(item.name)
    }
    if (localNames.size > 0) this.shadowed.push(localNames)
    try {
      this.emitBlockStatementBody(node, /*allowReturn*/ true)
    } finally {
      if (localNames.size > 0) this.shadowed.pop()
    }
  }

  private emitBlock(node: Block): void {
    if (node.body.length === 0) {
      this.write('(undefined)')
      return
    }
    // Local lets shadow same-named top-level cells inside this block —
    // push their names so identifier reads emit as bare idents (no .get()
    // injection). Pop in finally so style-block / multi-stmt branches all
    // honor it.
    const localNames = new Set<string>()
    for (const item of node.body) {
      if (item.kind === 'LocalLet') localNames.add(item.name)
    }
    if (localNames.size > 0) this.shadowed.push(localNames)
    try {
      this._emitBlockInner(node)
    } finally {
      if (localNames.size > 0) this.shadowed.pop()
    }
  }

  private _emitBlockInner(node: Block): void {
    // A block containing one or more `style { … }` blocks emits as an
    // array fragment so the renderer sees the main vnode and each style
    // vnode as siblings. LocalLet items inside such a block are still
    // ordinary const declarations; we wrap the whole thing in an IIFE
    // when needed below.
    const hasStyle = node.body.some((e) => e.kind === 'StyleBlock')
    const hasLocal = node.body.some((e) => e.kind === 'LocalLet')
    if (hasStyle && !hasLocal) {
      this.write('[')
      let first = true
      for (const item of node.body) {
        if (!first) this.write(', ')
        first = false
        this.emitExpr(item as Expr)
      }
      this.write(']')
      return
    }
    if (node.body.length === 1 && !hasLocal) {
      const only = node.body[0]
      if (!only) {
        this.write('(undefined)')
        return
      }
      this.write('(')
      this.emitExpr(only as Expr)
      this.write(')')
      return
    }
    // Multi-item path (or single-item-with-LocalLet): wrap in an IIFE.
    // LocalLet items emit as `const x = …;`; non-final expressions emit as
    // `expr;` for side effects; the FINAL non-LocalLet expression emits as
    // `return …`. If the trailing item is itself a LocalLet, the block
    // returns undefined.
    this.write('(() => {\n')
    let lastExprIdx = -1
    for (let i = node.body.length - 1; i >= 0; i--) {
      if (node.body[i]!.kind !== 'LocalLet') {
        lastExprIdx = i
        break
      }
    }
    for (let i = 0; i < node.body.length; i++) {
      const item = node.body[i]!
      this.write('  ')
      if (item.kind === 'LocalLet') {
        this.emitLocalLet(item as LocalLet)
        this.write(';\n')
      } else if (i === lastExprIdx) {
        // Inside an IIFE that mixes local-lets and a style block array
        // fragment, we still want the array shape — but only when the
        // final expression is the array fragment itself. Detect that
        // case via `hasStyle` and emit a special return shape.
        if (hasStyle) {
          this.write('return [')
          // Re-emit non-LocalLet items in source order as the array
          // fragment members. We'd already emitted the local-lets above.
          let firstArr = true
          for (const inner of node.body) {
            if (inner.kind === 'LocalLet') continue
            if (!firstArr) this.write(', ')
            firstArr = false
            this.emitExpr(inner as Expr)
          }
          this.write('];\n')
          break // we just emitted everything past the local-lets
        }
        // Trailing-position emit recognizes `throw …` / `return …` so
        // they emit as clean statements without the redundant IIFE
        // wrap that the expression-position code path uses.
        this.emitBlockTrailingExpr(item as Expr)
      } else {
        // Same statement-aware path for non-trailing items.
        this.emitBlockStmt(item as Expr)
      }
    }
    if (lastExprIdx === -1) this.write('  return undefined;\n')
    this.write('})()')
  }

  private emitLocalLet(node: LocalLet): void {
    this.write('const ')
    this.mark(node.nameStart, node.nameEnd, () => this.write(node.name))
    if (this.tsMode && node.type !== undefined) {
      this.write(`: ${node.type}`)
    }
    this.write(' = ')
    this.emitExpr(node.value)
  }

  private emitMarkdownBlock(node: MarkdownBlock): void {
    // Render the markdown source to HTML at compile time, then emit as
    // a `$static` vnode (M6.0 path). The runtime parses the html via
    // <template>.innerHTML — no per-render allocation, no markdown
    // parser at runtime.
    //
    // We dedent the markdown body before parsing because Tu source
    // typically nests `markdown { … }` under at least one indent level
    // — markdown-it's CommonMark behaviour treats 4-space-indented
    // lines as code blocks, which would mangle every nested paragraph.
    const md = getMd()
    const html = md.render(dedent(node.source))
    const wrapped = `<article class="tu-markdown">${html}</article>`
    this.write('h(')
    this.mark(node.start, node.end, () => this.write('"$static"'))
    this.write(', {}, [], ')
    this.write(JSON.stringify(wrapped))
    this.write(')')
  }

  private emitStyleBlock(node: StyleBlock): void {
    // Enforce M5/D: top-level rule selectors must be class-rooted.
    // Element selectors (`p { … }`) at top level escape the component's
    // hash scope and bleed into the page; users wanting them inside a
    // class should switch to CSS4 nesting (`.card { p { … } }`).
    const violation = findNonClassTopLevelSelector(node.css)
    if (violation !== null) {
      throw new Error(
        `top-level CSS rule must use a class selector (.foo); got "${violation}". ` +
          `Wrap element / id selectors inside a class block to use CSS nesting.`
      )
    }
    const ctx = this.currentScope()
    const css = ctx ? rewriteCss(node.css, ctx.declared, ctx.hash) : node.css
    this.write(`h("style", {}, [${JSON.stringify(css)}])`)
  }

  private emitClassRef(node: ClassRef): void {
    const ctx = this.currentScope()
    if (!ctx) {
      throw new Error(
        `class ref .${node.name} used outside a scoped component (component must contain a style { … } block)`
      )
    }
    if (!ctx.declared.has(node.name)) {
      throw new Error(
        `class ref .${node.name} is not declared in this component's style block`
      )
    }
    // Emit BOTH the original class name AND the hashed one (space-joined),
    // so consumers can target the unhashed `.block` from global CSS / dev-
    // tools / framework theming layers, while the component's own scoped
    // styles (which use the hashed name in selectors) stay isolated.
    this.mark(node.start, node.end, () =>
      this.write(JSON.stringify(`${node.name} ${node.name}-tu-${ctx.hash}`))
    )
  }

  private currentScope(): ScopeCtx | undefined {
    return this.scopes[this.scopes.length - 1]
  }

  private emitAssignExpr(node: AssignExpr): void {
    // A lambda parameter or `for` binder shadowing the cell — plain JS assign.
    for (let i = this.shadowed.length - 1; i >= 0; i--) {
      if (this.shadowed[i]?.has(node.target)) {
        this.write('(')
        this.mark(node.targetStart, node.targetEnd, () => this.write(node.target))
        this.write(' = ')
        this.emitExpr(node.value)
        this.write(')')
        return
      }
    }
    const kind = this.cells.get(node.target)
    if (kind === 'state') {
      this.mark(node.targetStart, node.targetEnd, () => this.write(node.target))
      this.write('.set(')
      this.emitExpr(node.value)
      this.write(')')
      return
    }
    if (kind === 'computed') {
      throw new Error(`cannot assign to computed cell '${node.target}'`)
    }
    if (kind === 'function') {
      throw new Error(`cannot assign to function binding '${node.target}'`)
    }
    // Unknown binding — emit a plain JS assignment so user-defined locals work.
    this.write('(')
    this.mark(node.targetStart, node.targetEnd, () => this.write(node.target))
    this.write(' = ')
    this.emitExpr(node.value)
    this.write(')')
  }

  private emitTagCall(node: TagCall): void {
    // Static-HTML subtree optimization (M6.0). When the whole TagCall is
    // statically determinable at compile time (no cell reads, no params,
    // no event handlers, no control flow, no nested components), serialize
    // it to an HTML string here and emit a single
    // `h("$static", {}, [], "<tag>…</tag>")` call. The runtime parses the
    // template once on mount and serves it verbatim during SSR — saving an
    // h() call + props object + children array per nested vnode.
    //
    // Subtree size threshold: skip if a single tag with at most one text
    // child — the parse cost wouldn't be worth the saved allocations.
    const ctx = this.currentScope()
    if (isStaticTree(node, ctx) && countStaticNodes(node) >= 3) {
      const html = renderStaticToHtml(node, ctx)
      this.write('h(')
      this.mark(node.tagStart, node.tagEnd, () => this.write('"$static"'))
      this.write(', {}, [], ')
      this.write(JSON.stringify(html))
      this.write(')')
      return
    }
    this.write('h(')
    // Mark the tag span so a TS error on the synthetic h() call's tag
    // argument lands on the source `div` / `.foo` token.
    this.mark(node.tagStart, node.tagEnd, () => this.write(JSON.stringify(node.tag)))
    this.write(', ')
    this.emitProps(node.props)
    this.write(', ')
    this.emitChildren(node.children)
    this.write(')')
  }

  private emitCallExpr(node: CallExpr): void {
    // Mark the callee so an error on the function lands on its source ident.
    this.mark(node.calleeStart, node.calleeEnd, () => this.write(node.callee))
    this.write('(')
    // M6.1 named-arg call: `Card(title: "hi", footer: …) { children }`
    // emits a single props object `Card({ title: "hi", footer: …,
    // children: [...] })`. The receiver lambda destructures the object;
    // every prop is optional by construction.
    if (node.namedArgs !== undefined) {
      this.write('{ ')
      for (let i = 0; i < node.namedArgs.length; i++) {
        if (i > 0) this.write(', ')
        const p = node.namedArgs[i]!
        this.write(`${JSON.stringify(p.name)}: `)
        this.emitExpr(p.value)
      }
      if (node.children !== undefined) {
        if (node.namedArgs.length > 0) this.write(', ')
        this.write('"children": [')
        for (let i = 0; i < node.children.length; i++) {
          if (i > 0) this.write(', ')
          this.emitExpr(node.children[i]!)
        }
        this.write(']')
      }
      this.write(' }')
      this.write(')')
      return
    }
    // Legacy positional call (M5.x BC).
    for (let i = 0; i < node.args.length; i++) {
      if (i > 0) this.write(', ')
      this.emitExpr(node.args[i]!)
    }
    // Component invocations carry a trailing children array. Emit
    // it as the last positional argument so a `let Card = (..., children)`
    // lambda can receive it.
    if (node.children !== undefined) {
      if (node.args.length > 0) this.write(', ')
      this.write('[')
      for (let i = 0; i < node.children.length; i++) {
        if (i > 0) this.write(', ')
        this.emitExpr(node.children[i]!)
      }
      this.write(']')
    }
    this.write(')')
  }

  private emitBinaryExpr(node: BinaryExpr): void {
    const op = BINARY_OP_JS[node.op]
    this.write('(')
    this.emitExpr(node.left)
    this.write(` ${op} `)
    this.emitExpr(node.right)
    this.write(')')
  }

  private emitIfExpr(node: IfExpr): void {
    this.write('(')
    this.emitExpr(node.cond)
    this.write(' ? ')
    this.emitExpr(node.then)
    this.write(' : ')
    if (node.else === undefined) this.write('undefined')
    else this.emitExpr(node.else)
    this.write(')')
  }

  private emitForExpr(node: ForExpr): void {
    this.write('Array.from(')
    this.emitExpr(node.iter)
    this.write(', (')
    this.mark(node.itemStart, node.itemEnd, () => this.write(node.item))
    this.write(') => ')
    this.shadowed.push(new Set([node.item]))
    try {
      this.emitExpr(node.body)
    } finally {
      this.shadowed.pop()
    }
    this.write(')')
  }

  private emitProps(props: Prop[]): void {
    if (props.length === 0) {
      this.write('{}')
      return
    }
    this.write('{ ')
    for (let i = 0; i < props.length; i++) {
      if (i > 0) this.write(', ')
      const p = props[i]!
      this.write(`${JSON.stringify(p.name)}: `)
      this.emitExpr(p.value)
    }
    this.write(' }')
  }

  private emitChildren(children: Child[]): void {
    if (children.length === 0) {
      this.write('[]')
      return
    }
    this.write('[')
    for (let i = 0; i < children.length; i++) {
      if (i > 0) this.write(', ')
      this.emitExpr(children[i]!)
    }
    this.write(']')
  }

  /**
   * Emit an identifier read. If the name refers to a State or Computed cell
   * and is NOT shadowed by an enclosing lambda parameter, emit `.get()`. The
   * source range is recorded only for the bare ident — `.get()` is synthetic
   * and shouldn't be highlighted by diagnostics.
   */
  private emitIdentRead(name: string, srcStart: number, srcEnd: number): void {
    for (let i = this.shadowed.length - 1; i >= 0; i--) {
      if (this.shadowed[i]?.has(name)) {
        this.mark(srcStart, srcEnd, () => this.write(name))
        return
      }
    }
    const kind = this.cells.get(name)
    if (kind === 'state' || kind === 'computed') {
      this.mark(srcStart, srcEnd, () => this.write(name))
      this.write('.get()')
      return
    }
    this.mark(srcStart, srcEnd, () => this.write(name))
  }
}

// ─── AST walkers (scope analysis) ──────────────────────────────────────────

function collectClassRefs(expr: Expr | Block | undefined, out: Set<string>): void {
  if (!expr) return
  switch (expr.kind) {
    case 'ClassRef':
      out.add(expr.name)
      return
    case 'TagCall':
      for (const p of expr.props) collectClassRefs(p.value, out)
      for (const c of expr.children) collectClassRefs(c as Expr, out)
      return
    case 'CallExpr':
      for (const a of expr.args) collectClassRefs(a, out)
      if (expr.children) for (const c of expr.children) collectClassRefs(c as Expr, out)
      return
    case 'BinaryExpr':
      collectClassRefs(expr.left, out)
      collectClassRefs(expr.right, out)
      return
    case 'Block':
      for (const e of expr.body) {
        if (e.kind === 'LocalLet') collectClassRefs(e.value, out)
        else collectClassRefs(e, out)
      }
      return
    case 'IfExpr':
      collectClassRefs(expr.cond, out)
      collectClassRefs(expr.then, out)
      if (expr.else) collectClassRefs(expr.else, out)
      return
    case 'ForExpr':
      collectClassRefs(expr.iter, out)
      collectClassRefs(expr.body, out)
      return
    case 'Lambda':
      collectClassRefs(expr.body, out)
      return
    case 'AssignExpr':
      collectClassRefs(expr.value, out)
      return
    case 'MemberAssignExpr':
      collectClassRefs(expr.target, out)
      collectClassRefs(expr.value, out)
      return
    case 'InvokeExpr':
      collectClassRefs(expr.callee, out)
      for (const a of expr.args) collectClassRefs(a, out)
      return
    case 'ArrayLit':
      for (const e of expr.elements) collectClassRefs(e, out)
      return
    case 'ObjectLit':
      for (const p of expr.properties) {
        if (p.kind === 'ObjectSpread') collectClassRefs(p.arg, out)
        else collectClassRefs(p.value, out)
      }
      return
    case 'MemberExpr':
      collectClassRefs(expr.object, out)
      return
    case 'MethodCallExpr':
      collectClassRefs(expr.object, out)
      for (const a of expr.args) collectClassRefs(a, out)
      return
    case 'UnaryExpr':
    case 'NonNullAssertExpr':
      collectClassRefs(expr.arg, out)
      return
    case 'IndexExpr':
      collectClassRefs(expr.object, out)
      collectClassRefs(expr.index, out)
      return
    case 'ThrowExpr':
      collectClassRefs(expr.arg, out)
      return
    case 'ReturnExpr':
      if (expr.value) collectClassRefs(expr.value, out)
      return
    case 'TryExpr':
      collectClassRefs(expr.body, out)
      if (expr.catchClause) collectClassRefs(expr.catchClause.body, out)
      if (expr.finallyClause) collectClassRefs(expr.finallyClause, out)
      return
    case 'TernaryExpr':
      collectClassRefs(expr.cond, out)
      collectClassRefs(expr.then, out)
      collectClassRefs(expr.else, out)
      return
    case 'NewExpr':
    case 'SpreadElement':
    case 'AwaitExpr':
    case 'ImportExpr':
      collectClassRefs(expr.arg, out)
      return
    case 'UpdateExpr':
      collectClassRefs(expr.arg, out)
      return
    case 'TemplateLit':
      for (const e of expr.expressions) collectClassRefs(e, out)
      return
    default:
      return
  }
}

function collectStyleBlockBodies(expr: Expr | Block | undefined, out: string[]): void {
  if (!expr) return
  switch (expr.kind) {
    case 'StyleBlock':
      out.push(expr.css)
      return
    case 'TagCall':
      for (const p of expr.props) collectStyleBlockBodies(p.value, out)
      for (const c of expr.children) collectStyleBlockBodies(c as Expr, out)
      return
    case 'CallExpr':
      for (const a of expr.args) collectStyleBlockBodies(a, out)
      if (expr.children) for (const c of expr.children) collectStyleBlockBodies(c as Expr, out)
      return
    case 'BinaryExpr':
      collectStyleBlockBodies(expr.left, out)
      collectStyleBlockBodies(expr.right, out)
      return
    case 'Block':
      for (const e of expr.body) {
        if (e.kind === 'LocalLet') collectStyleBlockBodies(e.value, out)
        else collectStyleBlockBodies(e, out)
      }
      return
    case 'IfExpr':
      collectStyleBlockBodies(expr.cond, out)
      collectStyleBlockBodies(expr.then, out)
      if (expr.else) collectStyleBlockBodies(expr.else, out)
      return
    case 'ForExpr':
      collectStyleBlockBodies(expr.iter, out)
      collectStyleBlockBodies(expr.body, out)
      return
    case 'Lambda':
      collectStyleBlockBodies(expr.body, out)
      return
    case 'AssignExpr':
      collectStyleBlockBodies(expr.value, out)
      return
    case 'MemberAssignExpr':
      collectStyleBlockBodies(expr.target, out)
      collectStyleBlockBodies(expr.value, out)
      return
    case 'InvokeExpr':
      collectStyleBlockBodies(expr.callee, out)
      for (const a of expr.args) collectStyleBlockBodies(a, out)
      return
    case 'ArrayLit':
      for (const e of expr.elements) collectStyleBlockBodies(e, out)
      return
    case 'ObjectLit':
      for (const p of expr.properties) {
        if (p.kind === 'ObjectSpread') collectStyleBlockBodies(p.arg, out)
        else collectStyleBlockBodies(p.value, out)
      }
      return
    case 'MemberExpr':
      collectStyleBlockBodies(expr.object, out)
      return
    case 'MethodCallExpr':
      collectStyleBlockBodies(expr.object, out)
      for (const a of expr.args) collectStyleBlockBodies(a, out)
      return
    case 'UnaryExpr':
    case 'NonNullAssertExpr':
      collectStyleBlockBodies(expr.arg, out)
      return
    case 'IndexExpr':
      collectStyleBlockBodies(expr.object, out)
      collectStyleBlockBodies(expr.index, out)
      return
    case 'ThrowExpr':
      collectStyleBlockBodies(expr.arg, out)
      return
    case 'ReturnExpr':
      if (expr.value) collectStyleBlockBodies(expr.value, out)
      return
    case 'TryExpr':
      collectStyleBlockBodies(expr.body, out)
      if (expr.catchClause) collectStyleBlockBodies(expr.catchClause.body, out)
      if (expr.finallyClause) collectStyleBlockBodies(expr.finallyClause, out)
      return
    case 'TernaryExpr':
      collectStyleBlockBodies(expr.cond, out)
      collectStyleBlockBodies(expr.then, out)
      collectStyleBlockBodies(expr.else, out)
      return
    case 'NewExpr':
    case 'SpreadElement':
    case 'UpdateExpr':
    case 'AwaitExpr':
    case 'ImportExpr':
      collectStyleBlockBodies(expr.arg, out)
      return
    case 'TemplateLit':
      for (const e of expr.expressions) collectStyleBlockBodies(e, out)
      return
    default:
      return
  }
}

// ─── CSS class scanner + rewriter ──────────────────────────────────────────

interface ClassToken {
  start: number
  end: number
  name: string
}

const GLOBAL_PREFIX = ':global('

/**
 * Scan a CSS text for `.classname` selector tokens. Skips over `"…"` / `'…'`
 * strings, `/* … *​/` block comments, and the interior of `:global(...)`
 * escape-hatch wrappers — those classes stay unscoped at runtime, so we
 * neither register them as "declared" nor rewrite them at emit time.
 */
function scanCssClasses(css: string): ClassToken[] {
  const out: ClassToken[] = []
  let i = 0
  while (i < css.length) {
    const c = css.charAt(i)
    if (c === '/' && css.charAt(i + 1) === '*') {
      const end = css.indexOf('*/', i + 2)
      if (end < 0) break
      i = end + 2
      continue
    }
    if (c === '"' || c === "'") {
      const quote = c
      i++
      while (i < css.length && css.charAt(i) !== quote) {
        if (css.charAt(i) === '\\') i++
        i++
      }
      if (i < css.length) i++
      continue
    }
    if (css.startsWith(GLOBAL_PREFIX, i)) {
      i = skipGlobalInterior(css, i)
      continue
    }
    if (c === '.' && i + 1 < css.length && isClassFirst(css.charAt(i + 1))) {
      const start = i
      i++ // skip the dot
      while (i < css.length && isClassPart(css.charAt(i))) i++
      out.push({ start, end: i, name: css.slice(start + 1, i) })
      continue
    }
    i++
  }
  return out
}

/**
 * `i` points at the leading `:` of `:global(`. Find the matching `)` and
 * return the index of the next char to scan — past the `)`. Tracks paren
 * depth so a nested `:is(...)` inside `:global(...)` doesn't terminate
 * the wrapper early.
 */
function skipGlobalInterior(css: string, start: number): number {
  let depth = 1
  let j = start + GLOBAL_PREFIX.length
  while (j < css.length && depth > 0) {
    const cc = css.charAt(j)
    if (cc === '(') depth++
    else if (cc === ')') depth--
    if (depth === 0) break
    j++
  }
  return j + 1 // past the matching `)`
}

function isClassFirst(c: string): boolean {
  return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c === '_' || c === '-'
}

function isClassPart(c: string): boolean {
  return isClassFirst(c) || (c >= '0' && c <= '9')
}

function findCssClasses(css: string): Set<string> {
  const out = new Set<string>()
  for (const tok of scanCssClasses(css)) out.add(tok.name)
  return out
}

/**
 * Rewrite `.declaredClass` selectors in `css` to `.declaredClass-tu-{hash}`.
 * Class names not in `declared` are left untouched (referring to global CSS).
 *
 * Also strips `:global(...)` wrappers from the output: the wrapper itself is
 * dropped while the contents pass through verbatim. Combined with the
 * scanner skipping global interiors, this gives the user an explicit
 * escape hatch for an otherwise-scoped selector.
 */
function rewriteCss(css: string, declared: Set<string>, hash: string): string {
  let out = ''
  let i = 0
  while (i < css.length) {
    const c = css.charAt(i)
    if (c === '/' && css.charAt(i + 1) === '*') {
      const end = css.indexOf('*/', i + 2)
      if (end < 0) {
        out += css.slice(i)
        break
      }
      out += css.slice(i, end + 2)
      i = end + 2
      continue
    }
    if (c === '"' || c === "'") {
      const quote = c
      const start = i
      i++
      while (i < css.length && css.charAt(i) !== quote) {
        if (css.charAt(i) === '\\') i++
        i++
      }
      if (i < css.length) i++
      out += css.slice(start, i)
      continue
    }
    if (css.startsWith(GLOBAL_PREFIX, i)) {
      // Strip the wrapper — emit the inner body as-is. Nested classes are
      // intentionally left unscoped (that's what :global means).
      const innerStart = i + GLOBAL_PREFIX.length
      const wrapperEnd = skipGlobalInterior(css, i)
      out += css.slice(innerStart, wrapperEnd - 1) // exclude the trailing `)`
      i = wrapperEnd
      continue
    }
    if (c === '.' && i + 1 < css.length && isClassFirst(css.charAt(i + 1))) {
      const start = i
      i++ // skip dot
      while (i < css.length && isClassPart(css.charAt(i))) i++
      const name = css.slice(start + 1, i)
      out += '.' + name
      if (declared.has(name)) out += `-tu-${hash}`
      continue
    }
    out += c
    i++
  }
  return out
}

/**
 * Walk the CSS body's top-level rules. A rule's "selector" is whatever
 * sits between the previous depth-0 `}` (or start) and the next `{`.
 * Comma-split each, trim, and check each piece starts with `.` (class
 * selector), `:global(` (escape hatch), or `@` (at-rule like `@media`).
 *
 * Returns the first offending selector text on violation, or `null` when
 * every top-level rule is class-rooted.
 *
 * Skips strings, comments, and `:global(...)` wrappers' interiors so a
 * `.foo > p` inside a global escape doesn't flag.
 */
function findNonClassTopLevelSelector(css: string): string | null {
  let buffer = ''
  let depth = 0
  let i = 0
  while (i < css.length) {
    const c = css.charAt(i)
    if (c === '/' && css.charAt(i + 1) === '*') {
      const end = css.indexOf('*/', i + 2)
      if (end < 0) break
      i = end + 2
      continue
    }
    if (c === '"' || c === "'") {
      const q = c
      i++
      while (i < css.length && css.charAt(i) !== q) {
        if (css.charAt(i) === '\\') i++
        i++
      }
      if (i < css.length) i++
      continue
    }
    if (c === '{') {
      if (depth === 0) {
        const v = checkSelectorList(buffer)
        if (v !== null) return v
        buffer = ''
      }
      depth++
      i++
      continue
    }
    if (c === '}') {
      depth--
      if (depth === 0) buffer = ''
      i++
      continue
    }
    if (depth === 0) buffer += c
    i++
  }
  return null
}

function checkSelectorList(raw: string): string | null {
  const trimmed = raw.trim()
  if (trimmed === '') return null
  // Comma-split. Doesn't fully respect parens (`:not(.a, .b)`), good
  // enough for V1 — common CSS rarely has commas inside top-level
  // pseudo-class args.
  const parts = trimmed.split(',').map((p) => p.trim()).filter(Boolean)
  for (const p of parts) {
    if (p.startsWith('.')) continue
    if (p.startsWith(':global(')) continue
    if (p.startsWith('@')) continue
    return p
  }
  return null
}

// ─── Static-HTML subtree optimization (M6.0) ───────────────────────────────
//
// When a TagCall subtree is fully statically determinable (no cell reads,
// no lambda params, no event handlers, no control flow, no nested
// components), the codegen serializes it to an HTML string at compile
// time and emits a single `h("$static", {}, [], html)` call. The runtime
// parses the template once on mount and reuses the resulting DOM root.
//
// Bounds (V1 MVP):
//   - Subtree must be a single TagCall as its root.
//   - All props must be literal (StringLit / NumberLit / true / declared
//     ClassRef). No cell-driven props, no event handlers (`on*`).
//   - Children must each be: StringLit, NumberLit, declared ClassRef, or
//     another static TagCall recursively. No idents (cell reads), no
//     calls, no if/for, no Lambda/Block/AssignExpr/ObjectLit/MemberExpr.
//   - Tag must NOT be `style` or `script` — raw-text elements have
//     different escape rules; the existing `emitStyleBlock` path already
//     handles `style { ... }` specially.
//
// ClassRef hashes are baked in here using the same dual-class output as
// `emitClassRef` (M5/F dual-class injection), so scoped CSS keeps lining
// up with the static markup.

const STATIC_VOID_ELEMENTS = new Set([
  'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
  'link', 'meta', 'source', 'track', 'wbr',
])

/** True iff the expression's runtime shape is fully known at compile time. */
function isStaticTree(expr: Expr | Child, scope: ScopeCtx | undefined): boolean {
  if (expr.kind === 'StringLit') return true
  if (expr.kind === 'NumberLit') return true
  if (expr.kind === 'ClassRef') {
    return scope !== undefined && scope.declared.has(expr.name)
  }
  if (expr.kind === 'TagCall') {
    if (expr.tag === 'style' || expr.tag === 'script') return false
    for (const p of expr.props) {
      if (isEventPropName(p.name)) return false
      if (!isStaticPropValue(p.value, scope)) return false
    }
    for (const c of expr.children) {
      if (!isStaticTree(c as Expr, scope)) return false
    }
    return true
  }
  return false
}

function isStaticPropValue(v: Expr, scope: ScopeCtx | undefined): boolean {
  if (v.kind === 'StringLit') return true
  if (v.kind === 'NumberLit') return true
  if (v.kind === 'ClassRef') {
    return scope !== undefined && scope.declared.has(v.name)
  }
  return false
}

function isEventPropName(name: string): boolean {
  if (name.length < 3) return false
  if (name.charAt(0) !== 'o' || name.charAt(1) !== 'n') return false
  const c = name.charCodeAt(2)
  return c >= 0x41 && c <= 0x5a // capital letter
}

/** Count tag/text/classref nodes in a static subtree — used for the
 *  "skip tiny optimizations" threshold. */
function countStaticNodes(expr: Expr | Child): number {
  if (expr.kind === 'TagCall') {
    let n = 1
    for (const c of expr.children) n += countStaticNodes(c as Expr)
    return n
  }
  return 1
}

/**
 * Serialize a known-static subtree to an HTML string. Mirror of
 * `renderVNode` from `@tu-lang/runtime`, but operating on AST nodes instead of
 * VNodes. Uses the same escape rules so the output round-trips through
 * `renderToString` without double-escaping.
 */
function renderStaticToHtml(expr: Expr | Child, scope: ScopeCtx | undefined): string {
  if (expr.kind === 'StringLit') return escapeStaticText(expr.value)
  if (expr.kind === 'NumberLit') return String(expr.value)
  if (expr.kind === 'ClassRef') {
    if (!scope) return escapeStaticText(expr.name)
    return escapeStaticText(`${expr.name} ${expr.name}-tu-${scope.hash}`)
  }
  if (expr.kind === 'TagCall') {
    let propStr = ''
    for (const p of expr.props) {
      const rendered = renderStaticPropValue(p.value, scope)
      if (rendered === null) continue // boolean false / null prop — drop
      if (rendered === '') {
        propStr += ` ${p.name}` // boolean true → bare attribute
      } else {
        propStr += ` ${p.name}="${escapeStaticAttr(rendered)}"`
      }
    }
    if (STATIC_VOID_ELEMENTS.has(expr.tag)) {
      return `<${expr.tag}${propStr}>`
    }
    let childStr = ''
    for (const c of expr.children) {
      childStr += renderStaticToHtml(c as Expr, scope)
    }
    return `<${expr.tag}${propStr}>${childStr}</${expr.tag}>`
  }
  // Should never reach — isStaticTree gates the kinds we accept.
  return ''
}

/** Returns the prop value as a string (escapable), or `null` to drop the
 *  prop entirely (false / null / undefined values), or `''` for a boolean
 *  `true` (emit as a bare attribute). */
function renderStaticPropValue(v: Expr, scope: ScopeCtx | undefined): string | null {
  if (v.kind === 'StringLit') return v.value
  if (v.kind === 'NumberLit') return String(v.value)
  if (v.kind === 'ClassRef') {
    if (!scope) return v.name
    return `${v.name} ${v.name}-tu-${scope.hash}`
  }
  return null
}

/** Recursive check: does `expr` contain a `throw` or `return` that
 *  would need to escape the surrounding lambda? Used by emitLambda to
 *  decide between expression-bodied and statement-bodied forms.
 *  Crosses into if-branches and try-catch arms (which may sit at
 *  statement positions inside the lambda); does **NOT** cross into
 *  nested Lambdas — those have their own return semantics. */
function containsControlFlow(expr: Expr): boolean {
  switch (expr.kind) {
    case 'ThrowExpr':
    case 'ReturnExpr':
      return true
    case 'IfExpr':
      if (containsControlFlow(expr.cond)) return true
      if (blockHasControlFlow(expr.then)) return true
      if (expr.else !== undefined) {
        if (expr.else.kind === 'IfExpr') return containsControlFlow(expr.else)
        if (blockHasControlFlow(expr.else)) return true
      }
      return false
    case 'TryExpr':
      if (blockHasControlFlow(expr.body)) return true
      if (expr.catchClause && blockHasControlFlow(expr.catchClause.body)) return true
      if (expr.finallyClause && blockHasControlFlow(expr.finallyClause)) return true
      return false
    case 'Block':
      return blockHasControlFlow(expr)
    case 'BinaryExpr':
      return containsControlFlow(expr.left) || containsControlFlow(expr.right)
    case 'UnaryExpr':
    case 'NonNullAssertExpr':
      return containsControlFlow(expr.arg)
    case 'AssignExpr':
      return containsControlFlow(expr.value)
    case 'MemberAssignExpr':
      return containsControlFlow(expr.target) || containsControlFlow(expr.value)
    case 'InvokeExpr':
      return containsControlFlow(expr.callee) || expr.args.some(containsControlFlow)
    case 'CallExpr':
      return expr.args.some(containsControlFlow)
    case 'MethodCallExpr':
      return containsControlFlow(expr.object) || expr.args.some(containsControlFlow)
    case 'MemberExpr':
      return containsControlFlow(expr.object)
    case 'IndexExpr':
      return containsControlFlow(expr.object) || containsControlFlow(expr.index)
    case 'ArrayLit':
      return expr.elements.some(containsControlFlow)
    case 'ObjectLit':
      return expr.properties.some((p) =>
        p.kind === 'ObjectSpread' ? containsControlFlow(p.arg) : containsControlFlow(p.value)
      )
    case 'TernaryExpr':
      return containsControlFlow(expr.cond) || containsControlFlow(expr.then) || containsControlFlow(expr.else)
    case 'NewExpr':
    case 'SpreadElement':
    case 'UpdateExpr':
    case 'AwaitExpr':
    case 'ImportExpr':
      return containsControlFlow(expr.arg)
    case 'TemplateLit':
      return expr.expressions.some(containsControlFlow)
    default:
      return false
  }
}

function blockHasControlFlow(b: Block): boolean {
  for (const item of b.body) {
    if (item.kind === 'LocalLet') {
      if (containsControlFlow(item.value)) return true
      continue
    }
    if (containsControlFlow(item as Expr)) return true
  }
  return false
}

/** Re-escape a decoded template-literal chunk so it round-trips through
 *  a JS template literal: `\``, `\$`, `\\` and the `${` opener. */
function escapeTemplateChunk(s: string): string {
  let out = ''
  for (let i = 0; i < s.length; i++) {
    const c = s.charAt(i)
    if (c === '`') out += '\\`'
    else if (c === '\\') out += '\\\\'
    else if (c === '$' && s.charAt(i + 1) === '{') {
      out += '\\${'
      i++ // skip the `{` we just emitted
    } else {
      out += c
    }
  }
  return out
}

function escapeStaticText(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function escapeStaticAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')
}

// ─── Markdown dedent (M6.3) ────────────────────────────────────────────────

/**
 * Strip the common leading-whitespace prefix from every non-blank line
 * of a multi-line string. Used by `markdown { … }` block emit so users
 * can indent the markdown body to match surrounding Tu code without
 * tripping CommonMark's "4-space-indent = code block" rule.
 *
 * Tabs are treated as 1 column for prefix calculation — same as
 * markdown-it's tokenizer treats them. Edge case: an entirely-blank
 * input returns empty string.
 */
function dedent(source: string): string {
  const lines = source.split('\n')
  let minIndent = Infinity
  for (const line of lines) {
    if (line.trim() === '') continue
    const m = line.match(/^[ \t]*/)
    const len = m ? m[0].length : 0
    if (len < minIndent) minIndent = len
  }
  if (!isFinite(minIndent) || minIndent === 0) return source
  return lines.map((l) => (l.length >= minIndent ? l.slice(minIndent) : l)).join('\n')
}

// ─── Hash ───────────────────────────────────────────────────────────────────

/** FNV-1a 32-bit, returned as the leading 6 hex digits. */
function fnv1a6(input: string): string {
  let h = 0x811c9dc5
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  return (h >>> 0).toString(16).padStart(8, '0').slice(0, 6)
}

// ─── Source map (V3) ───────────────────────────────────────────────────────

const VLQ_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

function encodeVLQ(n: number): string {
  let v = n < 0 ? ((-n) << 1) | 1 : n << 1
  let out = ''
  do {
    let digit = v & 0b11111
    v >>>= 5
    if (v > 0) digit |= 0b100000
    out += VLQ_CHARS.charAt(digit)
  } while (v > 0)
  return out
}

/**
 * Build a V3 source map from the per-statement and per-token mapping anchors.
 * Token mappings are folded in as additional segments (start position only —
 * V3 has no native end-of-segment representation; the LSP consumes the
 * richer `tokenMappings` list directly for diagnostic-range translation).
 */
function buildV3Map(
  stmtMappings: StmtMapping[],
  tokenMappings: TokenMapping[],
  generated: string,
  source: string,
  filename: string
): SourceMapV3 {
  const totalGenLines = generated === '' ? 0 : generated.split('\n').length
  // Group all mappings by generated line. Both stmt anchors and token spans
  // contribute one segment each (token spans use their start position).
  const byLine = new Map<number, { genCol: number; srcLine: number; srcCol: number }[]>()
  const push = (jsOffset: number, srcOffset: number) => {
    const gen = lineColAt(generated, jsOffset)
    const src = lineColAt(source, srcOffset)
    const list = byLine.get(gen.line - 1) ?? []
    list.push({ genCol: gen.col - 1, srcLine: src.line - 1, srcCol: src.col - 1 })
    byLine.set(gen.line - 1, list)
  }
  for (const m of stmtMappings) push(m.jsOffset, m.srcOffset)
  for (const t of tokenMappings) push(t.jsStart, t.srcStart)
  // VLQ-encode segments line-by-line. genCol resets each line; srcLine/srcCol
  // are relative across the whole map.
  const out: string[] = []
  let prevSrcLine = 0
  let prevSrcCol = 0
  for (let line = 0; line < totalGenLines; line++) {
    const segs = byLine.get(line) ?? []
    segs.sort((a, b) => a.genCol - b.genCol)
    let prevGenCol = 0
    const segStrs: string[] = []
    for (const seg of segs) {
      let s = ''
      s += encodeVLQ(seg.genCol - prevGenCol)
      s += encodeVLQ(0) // sources index (we only ever have one source)
      s += encodeVLQ(seg.srcLine - prevSrcLine)
      s += encodeVLQ(seg.srcCol - prevSrcCol)
      segStrs.push(s)
      prevGenCol = seg.genCol
      prevSrcLine = seg.srcLine
      prevSrcCol = seg.srcCol
    }
    out.push(segStrs.join(','))
  }
  return {
    version: 3,
    file: filename,
    sources: [filename],
    sourcesContent: [source],
    names: [],
    mappings: out.join(';'),
  }
}

/** Base64-encode a UTF-8 string. Works in Node (Buffer) and the browser (btoa). */
function base64Encode(s: string): string {
  if (typeof Buffer !== 'undefined') {
    return Buffer.from(s, 'utf8').toString('base64')
  }
  // Browser fallback — `btoa` only handles bytes in 0x00..0xFF, so we
  // funnel UTF-8 bytes through a Latin-1 string first.
  const bytes = new TextEncoder().encode(s)
  let bin = ''
  for (const b of bytes) bin += String.fromCharCode(b)
  return btoa(bin)
}
