import type {
  AssignExpr,
  BinaryExpr,
  BinaryOp,
  Block,
  CallExpr,
  Child,
  ClassRef,
  Expr,
  ForExpr,
  IfExpr,
  Lambda,
  Program,
  Prop,
  Stmt,
  StyleBlock,
  TagCall,
} from './ast.js'
import { lineColAt } from './diagnostics.js'

const RUNTIME_IMPORT = `import { h, Signal } from '@tu/runtime'`

export interface SourceMapV3 {
  version: 3
  file?: string
  sources: string[]
  sourcesContent: string[]
  names: string[]
  mappings: string
}

/**
 * A finer-grained mapping than `StmtMapping`: ties a span of generated bytes
 * to a span of source bytes. Codegen records one of these per emitted leaf
 * token (identifiers, literals, etc.) so the LSP can squiggle the offending
 * token instead of the whole `let` header.
 *
 * Spans are byte ranges; `srcEnd` is exclusive. The LSP's diagnostic-range
 * mapping consumes this list directly (it doesn't go through V3 VLQ encoding,
 * since V3 segments don't carry an explicit source-end).
 */
export interface TokenMapping {
  /** Byte offset of the span's first character in the generated code. */
  jsStart: number
  /** Byte offset after the span's last character in the generated code. */
  jsEnd: number
  /** Byte offset of the span's first character in the `.tu` source. */
  srcStart: number
  /** Byte offset after the span's last character in the `.tu` source. */
  srcEnd: number
}

/**
 * Top-level binding kinds — drives whether an identifier read becomes
 * `name.get()` or stays as a plain reference.
 */
export type CellKind = 'state' | 'computed' | 'function'

/** Tu `==` / `!=` map to JS strict equality to avoid coercion surprises. */
const BINARY_OP_JS: Record<BinaryOp, string> = {
  '+': '+', '-': '-', '*': '*', '/': '/', '%': '%',
  '==': '===', '!=': '!==',
  '<': '<', '<=': '<=', '>': '>', '>=': '>=',
}

/** Per-component scoping state. Populated for any top-level `let X = (…) => { … }`
 * whose body contains at least one ClassRef. The hash is the suffix appended
 * to every declared class name in both markup and style block, so the markup
 * `.foo` reference resolves to the same hashed string as the style block's
 * `.foo` selector. */
interface ScopeCtx {
  hash: string
  declared: Set<string>
}

interface StmtMapping {
  /** Byte offset of the statement's first character in the generated JS. */
  jsOffset: number
  /** Byte offset of the statement's `let` keyword in the source. */
  srcOffset: number
}

interface BuildResult {
  code: string
  stmtMappings: StmtMapping[]
  tokenMappings: TokenMapping[]
}

/**
 * Per-emit options that the rest of the toolchain (LSP, CLI, vite plugin)
 * uses to give codegen extra context it can't derive from a single source
 * file.
 */
export interface CodegenOptions {
  /**
   * Per-imported-name classification. The compiler defaults to `'function'`
   * for any name brought in by `import { X } from "./M.tu"` because, looking
   * at the importing source alone, it can't tell what kind `X` was declared
   * as in the exporting module. Callers who DO know (the LSP's shadow graph,
   * the CLI's BFS, the vite plugin's resolver) pass the map here so reads of
   * imported state / computed cells emit `X.get()` instead of `X` — fixing
   * the M2.1 reactivity bug.
   */
  importedNameKinds?: ReadonlyMap<string, CellKind>
}

function buildBody(program: Program, tsMode: boolean, opts?: CodegenOptions): BuildResult {
  const cells = analyzeProgram(program, opts?.importedNameKinds)
  const scopes = analyzeScopedComponents(program)
  const cg = new Codegen(cells, scopes, tsMode)
  cg.write(`${RUNTIME_IMPORT}\n\n`)
  for (const stmt of program.body) {
    // Type aliases erase entirely in JS mode — they have no runtime presence.
    if (stmt.kind === 'TypeAlias' && !tsMode) continue
    cg.recordStmtMapping(stmt.start)
    cg.emitStmt(stmt)
    cg.write('\n')
  }
  return cg.finish()
}

export function generate(program: Program, opts?: CodegenOptions): string {
  return buildBody(program, false, opts).code
}

/**
 * Generate JS with a V3 source map. The returned code carries an inline
 * `//# sourceMappingURL=` data-URL footer; the same map is also returned
 * separately for tooling that consumes it programmatically. The richer
 * per-token mapping list is exposed alongside for the LSP / type-checker.
 */
export function generateWithMap(
  program: Program,
  source: string,
  filename?: string,
  opts?: CodegenOptions
): { code: string; map: SourceMapV3; tokenMappings: TokenMapping[] } {
  const result = buildBody(program, false, opts)
  const sourceName = filename ?? 'input.tu'
  const map = buildV3Map(result.stmtMappings, result.tokenMappings, result.code, source, sourceName)
  const inline = base64Encode(JSON.stringify(map))
  const footer = `//# sourceMappingURL=data:application/json;charset=utf-8;base64,${inline}\n`
  return { code: result.code + footer, map, tokenMappings: result.tokenMappings }
}

/**
 * Generate TypeScript source with a V3 source map. Same semantics as
 * `generateWithMap` but lambda parameter type annotations from the Tu source
 * are preserved (`(name: string)` instead of `(name)`), so tsserver can infer
 * the rest.
 */
export function generateTSWithMap(
  program: Program,
  source: string,
  filename?: string,
  opts?: CodegenOptions
): { code: string; map: SourceMapV3; tokenMappings: TokenMapping[] } {
  const result = buildBody(program, true, opts)
  const sourceName = filename ?? 'input.tu'
  const map = buildV3Map(result.stmtMappings, result.tokenMappings, result.code, source, sourceName)
  const inline = base64Encode(JSON.stringify(map))
  const footer = `//# sourceMappingURL=data:application/json;charset=utf-8;base64,${inline}\n`
  return { code: result.code + footer, map, tokenMappings: result.tokenMappings }
}

function analyzeProgram(
  program: Program,
  importedNameKinds?: ReadonlyMap<string, CellKind>
): Map<string, CellKind> {
  const cells = new Map<string, CellKind>()
  for (const stmt of program.body) {
    if (stmt.kind === 'LetDecl') {
      cells.set(stmt.name, classifyValue(stmt.value))
    }
    // Imported names: prefer the caller-provided kind (state / computed /
    // function); otherwise default to 'function' for the standalone-compile
    // path that has no graph view.
    if (stmt.kind === 'ImportDecl') {
      for (const name of stmt.names) {
        cells.set(name, importedNameKinds?.get(name) ?? 'function')
      }
    }
  }
  return cells
}

/** Public re-export so callers (LSP, CLI) can build the importedNameKinds map. */
export function classifyTopLevel(value: Expr): CellKind {
  return classifyValue(value)
}

function classifyValue(expr: Expr): CellKind {
  if (expr.kind === 'Lambda') return 'function'
  if (expr.kind === 'CallExpr' && expr.callee === 'computed') return 'computed'
  return 'state'
}

function analyzeScopedComponents(program: Program): Map<string, ScopeCtx> {
  const out = new Map<string, ScopeCtx>()
  for (const stmt of program.body) {
    if (stmt.kind !== 'LetDecl') continue
    if (stmt.value.kind !== 'Lambda') continue
    const refs = new Set<string>()
    collectClassRefs(stmt.value.body, refs)
    if (refs.size === 0) continue
    const styleBodies: string[] = []
    collectStyleBlockBodies(stmt.value.body, styleBodies)
    const declared = new Set<string>()
    for (const css of styleBodies) {
      for (const c of findCssClasses(css)) declared.add(c)
    }
    const hash = fnv1a6(`${stmt.name} ${styleBodies.join(' ')}`)
    out.set(stmt.name, { hash, declared })
  }
  return out
}

class Codegen {
  /** Stack of binding-name sets shadowing top-level cells (innermost last). */
  private readonly shadowed: Set<string>[] = []
  /** Stack of scoped-component contexts pushed at LetDecl emit time. */
  private readonly scopes: ScopeCtx[] = []
  /** Streaming output buffer. */
  private buffer = ''
  /** Per-statement mapping anchors (one per top-level statement). */
  private readonly stmtMappings: StmtMapping[] = []
  /** Per-token mapping spans (one per emitted leaf-ish source span). */
  private readonly tokenMappings: TokenMapping[] = []

  constructor(
    private readonly cells: Map<string, CellKind>,
    private readonly scopedComponents: Map<string, ScopeCtx>,
    private readonly tsMode: boolean = false
  ) {}

  write(text: string): void {
    this.buffer += text
  }

  recordStmtMapping(srcOffset: number): void {
    this.stmtMappings.push({ jsOffset: this.buffer.length, srcOffset })
  }

  /**
   * Run `fn` and record a TokenMapping spanning the byte range `fn` writes
   * into the buffer. The mapping ties that generated span back to
   * `[srcStart, srcEnd)` in the `.tu` source.
   */
  private mark(srcStart: number, srcEnd: number, fn: () => void): void {
    const jsStart = this.buffer.length
    fn()
    const jsEnd = this.buffer.length
    if (jsEnd > jsStart) {
      this.tokenMappings.push({ jsStart, jsEnd, srcStart, srcEnd })
    }
  }

  finish(): BuildResult {
    return {
      code: this.buffer,
      stmtMappings: this.stmtMappings,
      tokenMappings: this.tokenMappings,
    }
  }

  emitStmt(stmt: Stmt): void {
    if (stmt.kind === 'ImportDecl') {
      const src = this.rewriteSource(stmt.source)
      this.write(`import { ${stmt.names.join(', ')} } from ${JSON.stringify(src)}`)
      return
    }
    if (stmt.kind === 'ReExportDecl') {
      const src = this.rewriteSource(stmt.source)
      this.write(`export { ${stmt.names.join(', ')} } from ${JSON.stringify(src)}`)
      return
    }
    if (stmt.kind === 'TypeAlias') {
      // Only reached in TS mode; buildBody skips this stmt in JS mode.
      const prefix = stmt.exported ? 'export type' : 'type'
      this.write(`${prefix} `)
      this.mark(stmt.nameStart, stmt.nameEnd, () => this.write(stmt.name))
      this.write(' = ')
      this.mark(stmt.typeStart, stmt.typeEnd, () => this.write(stmt.type))
      return
    }
    const decl = stmt
    const prefix = decl.exported ? 'export const' : 'const'
    const kind = this.cells.get(decl.name) ?? 'state'
    const ctx = this.scopedComponents.get(decl.name)
    if (ctx) this.scopes.push(ctx)
    try {
      // M3.9: for an exported lambda with all-typed params, emit a named
      // `${Name}Props` interface BEFORE the const so downstream consumers
      // (TS code reading the .d.ts) get a reusable shape. Lambdas with any
      // untyped param are skipped — we don't want to invent `unknown` fields.
      if (
        this.tsMode &&
        decl.exported &&
        decl.value.kind === 'Lambda' &&
        decl.value.params.length >= 1 &&
        decl.value.params.every((p) => p.type !== undefined)
      ) {
        this.write(`export interface ${decl.name}Props { `)
        for (let i = 0; i < decl.value.params.length; i++) {
          if (i > 0) this.write('; ')
          const p = decl.value.params[i]!
          this.mark(p.nameStart, p.nameEnd, () => this.write(p.name))
          this.write(`: ${p.type}`)
        }
        this.write(' }\n')
      }
      this.write(`${prefix} `)
      // Mark the bound name so a TS error on `count` lands on the source `count`.
      this.mark(decl.nameStart, decl.nameEnd, () => this.write(decl.name))
      // M2.2: emit a TS type annotation when the user supplied one. Lambdas
      // pass through as-is; state / computed cells get the declared type
      // wrapped in their Signal box so the variable's actual type matches.
      if (this.tsMode && decl.type !== undefined) {
        if (kind === 'function') this.write(`: ${decl.type}`)
        else if (kind === 'computed') this.write(`: Signal.Computed<${decl.type}>`)
        else this.write(`: Signal.State<${decl.type}>`)
      }
      this.write(' = ')
      if (kind === 'function') {
        this.emitExpr(decl.value)
        return
      }
      if (kind === 'computed') {
        const v = decl.value as CallExpr
        const arg = v.args[0]
        this.write('new Signal.Computed(() => ')
        if (arg) this.emitExpr(arg)
        else this.write('undefined')
        this.write(')')
        return
      }
      // state
      this.write('new Signal.State(')
      this.emitExpr(decl.value)
      this.write(')')
    } finally {
      if (ctx) this.scopes.pop()
    }
  }

  /**
   * In TS-emit mode, rewrite a `./foo.tu` import source to `./foo.ts` so
   * tsserver resolves the sibling shadow file. Other extensions and
   * non-relative paths pass through unchanged.
   */
  private rewriteSource(source: string): string {
    if (this.tsMode && source.endsWith('.tu')) {
      return source.slice(0, -'.tu'.length) + '.ts'
    }
    return source
  }

  emitExpr(expr: Expr): void {
    switch (expr.kind) {
      case 'Lambda':
        this.emitLambda(expr)
        return
      case 'TagCall':
        this.emitTagCall(expr)
        return
      case 'CallExpr':
        this.emitCallExpr(expr)
        return
      case 'BinaryExpr':
        this.emitBinaryExpr(expr)
        return
      case 'StringLit':
        this.mark(expr.start, expr.end, () => this.write(JSON.stringify(expr.value)))
        return
      case 'NumberLit':
        this.mark(expr.start, expr.end, () => this.write(String(expr.value)))
        return
      case 'Ident':
        this.emitIdentRead(expr.name, expr.start, expr.end)
        return
      case 'Block':
        this.emitBlock(expr)
        return
      case 'IfExpr':
        this.emitIfExpr(expr)
        return
      case 'ForExpr':
        this.emitForExpr(expr)
        return
      case 'StyleBlock':
        this.emitStyleBlock(expr)
        return
      case 'AssignExpr':
        this.emitAssignExpr(expr)
        return
      case 'ClassRef':
        this.emitClassRef(expr)
        return
    }
  }

  private emitLambda(node: Lambda): void {
    const paramNames = node.params.map((p) => p.name)
    this.shadowed.push(new Set(paramNames))
    try {
      this.write('(')
      for (let i = 0; i < node.params.length; i++) {
        if (i > 0) this.write(', ')
        const p = node.params[i]!
        // Mark the param name so a TS error on the param identifier maps
        // back to its source position.
        this.mark(p.nameStart, p.nameEnd, () => this.write(p.name))
        // In TS mode, preserve `: type` annotations from the Tu source so
        // tsserver can drive IDE features and `.d.ts` generation. In JS mode
        // (default), the names alone are emitted; types are erased.
        if (this.tsMode && p.type !== undefined) {
          this.write(`: ${p.type}`)
        }
      }
      this.write(') => ')
      this.emitExpr(node.body)
    } finally {
      this.shadowed.pop()
    }
  }

  private emitBlock(node: Block): void {
    if (node.body.length === 0) {
      this.write('(undefined)')
      return
    }
    // A block containing one or more `style { … }` blocks emits as an array
    // fragment so each item (the main vnode + each style vnode) reaches the
    // renderer. The runtime flattens array children, so `[mainVNode, styleVNode]`
    // renders as siblings.
    if (node.body.some((e) => e.kind === 'StyleBlock')) {
      this.write('[')
      for (let i = 0; i < node.body.length; i++) {
        if (i > 0) this.write(', ')
        this.emitExpr(node.body[i]!)
      }
      this.write(']')
      return
    }
    if (node.body.length === 1) {
      const only = node.body[0]
      if (!only) {
        this.write('(undefined)')
        return
      }
      this.write('(')
      this.emitExpr(only)
      this.write(')')
      return
    }
    this.write('(() => {\n')
    for (let i = 0; i < node.body.length - 1; i++) {
      this.write('  ')
      this.emitExpr(node.body[i]!)
      this.write(';\n')
    }
    const last = node.body[node.body.length - 1]
    if (!last) {
      this.write('  return undefined;\n})()')
      return
    }
    this.write('  return ')
    this.emitExpr(last)
    this.write(';\n})()')
  }

  private emitStyleBlock(node: StyleBlock): void {
    const ctx = this.currentScope()
    const css = ctx ? rewriteCss(node.css, ctx.declared, ctx.hash) : node.css
    this.write(`h("style", {}, [${JSON.stringify(css)}])`)
  }

  private emitClassRef(node: ClassRef): void {
    const ctx = this.currentScope()
    if (!ctx) {
      throw new Error(
        `class ref .${node.name} used outside a scoped component (component must contain a style { … } block)`
      )
    }
    if (!ctx.declared.has(node.name)) {
      throw new Error(
        `class ref .${node.name} is not declared in this component's style block`
      )
    }
    this.mark(node.start, node.end, () =>
      this.write(JSON.stringify(`${node.name}-tu-${ctx.hash}`))
    )
  }

  private currentScope(): ScopeCtx | undefined {
    return this.scopes[this.scopes.length - 1]
  }

  private emitAssignExpr(node: AssignExpr): void {
    // A lambda parameter or `for` binder shadowing the cell — plain JS assign.
    for (let i = this.shadowed.length - 1; i >= 0; i--) {
      if (this.shadowed[i]?.has(node.target)) {
        this.write('(')
        this.mark(node.targetStart, node.targetEnd, () => this.write(node.target))
        this.write(' = ')
        this.emitExpr(node.value)
        this.write(')')
        return
      }
    }
    const kind = this.cells.get(node.target)
    if (kind === 'state') {
      this.mark(node.targetStart, node.targetEnd, () => this.write(node.target))
      this.write('.set(')
      this.emitExpr(node.value)
      this.write(')')
      return
    }
    if (kind === 'computed') {
      throw new Error(`cannot assign to computed cell '${node.target}'`)
    }
    if (kind === 'function') {
      throw new Error(`cannot assign to function binding '${node.target}'`)
    }
    // Unknown binding — emit a plain JS assignment so user-defined locals work.
    this.write('(')
    this.mark(node.targetStart, node.targetEnd, () => this.write(node.target))
    this.write(' = ')
    this.emitExpr(node.value)
    this.write(')')
  }

  private emitTagCall(node: TagCall): void {
    this.write('h(')
    // Mark the tag span so a TS error on the synthetic h() call's tag
    // argument lands on the source `div` / `.foo` token.
    this.mark(node.tagStart, node.tagEnd, () => this.write(JSON.stringify(node.tag)))
    this.write(', ')
    this.emitProps(node.props)
    this.write(', ')
    this.emitChildren(node.children)
    this.write(')')
  }

  private emitCallExpr(node: CallExpr): void {
    // Mark the callee so an error on the function lands on its source ident.
    this.mark(node.calleeStart, node.calleeEnd, () => this.write(node.callee))
    this.write('(')
    for (let i = 0; i < node.args.length; i++) {
      if (i > 0) this.write(', ')
      this.emitExpr(node.args[i]!)
    }
    this.write(')')
  }

  private emitBinaryExpr(node: BinaryExpr): void {
    const op = BINARY_OP_JS[node.op]
    this.write('(')
    this.emitExpr(node.left)
    this.write(` ${op} `)
    this.emitExpr(node.right)
    this.write(')')
  }

  private emitIfExpr(node: IfExpr): void {
    this.write('(')
    this.emitExpr(node.cond)
    this.write(' ? ')
    this.emitExpr(node.then)
    this.write(' : ')
    if (node.else === undefined) this.write('undefined')
    else this.emitExpr(node.else)
    this.write(')')
  }

  private emitForExpr(node: ForExpr): void {
    this.write('Array.from(')
    this.emitExpr(node.iter)
    this.write(', (')
    this.mark(node.itemStart, node.itemEnd, () => this.write(node.item))
    this.write(') => ')
    this.shadowed.push(new Set([node.item]))
    try {
      this.emitExpr(node.body)
    } finally {
      this.shadowed.pop()
    }
    this.write(')')
  }

  private emitProps(props: Prop[]): void {
    if (props.length === 0) {
      this.write('{}')
      return
    }
    this.write('{ ')
    for (let i = 0; i < props.length; i++) {
      if (i > 0) this.write(', ')
      const p = props[i]!
      this.write(`${JSON.stringify(p.name)}: `)
      this.emitExpr(p.value)
    }
    this.write(' }')
  }

  private emitChildren(children: Child[]): void {
    if (children.length === 0) {
      this.write('[]')
      return
    }
    this.write('[')
    for (let i = 0; i < children.length; i++) {
      if (i > 0) this.write(', ')
      this.emitExpr(children[i]!)
    }
    this.write(']')
  }

  /**
   * Emit an identifier read. If the name refers to a State or Computed cell
   * and is NOT shadowed by an enclosing lambda parameter, emit `.get()`. The
   * source range is recorded only for the bare ident — `.get()` is synthetic
   * and shouldn't be highlighted by diagnostics.
   */
  private emitIdentRead(name: string, srcStart: number, srcEnd: number): void {
    for (let i = this.shadowed.length - 1; i >= 0; i--) {
      if (this.shadowed[i]?.has(name)) {
        this.mark(srcStart, srcEnd, () => this.write(name))
        return
      }
    }
    const kind = this.cells.get(name)
    if (kind === 'state' || kind === 'computed') {
      this.mark(srcStart, srcEnd, () => this.write(name))
      this.write('.get()')
      return
    }
    this.mark(srcStart, srcEnd, () => this.write(name))
  }
}

// ─── AST walkers (scope analysis) ──────────────────────────────────────────

function collectClassRefs(expr: Expr | Block | undefined, out: Set<string>): void {
  if (!expr) return
  switch (expr.kind) {
    case 'ClassRef':
      out.add(expr.name)
      return
    case 'TagCall':
      for (const p of expr.props) collectClassRefs(p.value, out)
      for (const c of expr.children) collectClassRefs(c as Expr, out)
      return
    case 'CallExpr':
      for (const a of expr.args) collectClassRefs(a, out)
      return
    case 'BinaryExpr':
      collectClassRefs(expr.left, out)
      collectClassRefs(expr.right, out)
      return
    case 'Block':
      for (const e of expr.body) collectClassRefs(e, out)
      return
    case 'IfExpr':
      collectClassRefs(expr.cond, out)
      collectClassRefs(expr.then, out)
      if (expr.else) collectClassRefs(expr.else, out)
      return
    case 'ForExpr':
      collectClassRefs(expr.iter, out)
      collectClassRefs(expr.body, out)
      return
    case 'Lambda':
      collectClassRefs(expr.body, out)
      return
    case 'AssignExpr':
      collectClassRefs(expr.value, out)
      return
    default:
      return
  }
}

function collectStyleBlockBodies(expr: Expr | Block | undefined, out: string[]): void {
  if (!expr) return
  switch (expr.kind) {
    case 'StyleBlock':
      out.push(expr.css)
      return
    case 'TagCall':
      for (const p of expr.props) collectStyleBlockBodies(p.value, out)
      for (const c of expr.children) collectStyleBlockBodies(c as Expr, out)
      return
    case 'CallExpr':
      for (const a of expr.args) collectStyleBlockBodies(a, out)
      return
    case 'BinaryExpr':
      collectStyleBlockBodies(expr.left, out)
      collectStyleBlockBodies(expr.right, out)
      return
    case 'Block':
      for (const e of expr.body) collectStyleBlockBodies(e, out)
      return
    case 'IfExpr':
      collectStyleBlockBodies(expr.cond, out)
      collectStyleBlockBodies(expr.then, out)
      if (expr.else) collectStyleBlockBodies(expr.else, out)
      return
    case 'ForExpr':
      collectStyleBlockBodies(expr.iter, out)
      collectStyleBlockBodies(expr.body, out)
      return
    case 'Lambda':
      collectStyleBlockBodies(expr.body, out)
      return
    case 'AssignExpr':
      collectStyleBlockBodies(expr.value, out)
      return
    default:
      return
  }
}

// ─── CSS class scanner + rewriter ──────────────────────────────────────────

interface ClassToken {
  start: number
  end: number
  name: string
}

const GLOBAL_PREFIX = ':global('

/**
 * Scan a CSS text for `.classname` selector tokens. Skips over `"…"` / `'…'`
 * strings, `/* … *​/` block comments, and the interior of `:global(...)`
 * escape-hatch wrappers — those classes stay unscoped at runtime, so we
 * neither register them as "declared" nor rewrite them at emit time.
 */
function scanCssClasses(css: string): ClassToken[] {
  const out: ClassToken[] = []
  let i = 0
  while (i < css.length) {
    const c = css.charAt(i)
    if (c === '/' && css.charAt(i + 1) === '*') {
      const end = css.indexOf('*/', i + 2)
      if (end < 0) break
      i = end + 2
      continue
    }
    if (c === '"' || c === "'") {
      const quote = c
      i++
      while (i < css.length && css.charAt(i) !== quote) {
        if (css.charAt(i) === '\\') i++
        i++
      }
      if (i < css.length) i++
      continue
    }
    if (css.startsWith(GLOBAL_PREFIX, i)) {
      i = skipGlobalInterior(css, i)
      continue
    }
    if (c === '.' && i + 1 < css.length && isClassFirst(css.charAt(i + 1))) {
      const start = i
      i++ // skip the dot
      while (i < css.length && isClassPart(css.charAt(i))) i++
      out.push({ start, end: i, name: css.slice(start + 1, i) })
      continue
    }
    i++
  }
  return out
}

/**
 * `i` points at the leading `:` of `:global(`. Find the matching `)` and
 * return the index of the next char to scan — past the `)`. Tracks paren
 * depth so a nested `:is(...)` inside `:global(...)` doesn't terminate
 * the wrapper early.
 */
function skipGlobalInterior(css: string, start: number): number {
  let depth = 1
  let j = start + GLOBAL_PREFIX.length
  while (j < css.length && depth > 0) {
    const cc = css.charAt(j)
    if (cc === '(') depth++
    else if (cc === ')') depth--
    if (depth === 0) break
    j++
  }
  return j + 1 // past the matching `)`
}

function isClassFirst(c: string): boolean {
  return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c === '_' || c === '-'
}

function isClassPart(c: string): boolean {
  return isClassFirst(c) || (c >= '0' && c <= '9')
}

function findCssClasses(css: string): Set<string> {
  const out = new Set<string>()
  for (const tok of scanCssClasses(css)) out.add(tok.name)
  return out
}

/**
 * Rewrite `.declaredClass` selectors in `css` to `.declaredClass-tu-{hash}`.
 * Class names not in `declared` are left untouched (referring to global CSS).
 *
 * Also strips `:global(...)` wrappers from the output: the wrapper itself is
 * dropped while the contents pass through verbatim. Combined with the
 * scanner skipping global interiors, this gives the user an explicit
 * escape hatch for an otherwise-scoped selector.
 */
function rewriteCss(css: string, declared: Set<string>, hash: string): string {
  let out = ''
  let i = 0
  while (i < css.length) {
    const c = css.charAt(i)
    if (c === '/' && css.charAt(i + 1) === '*') {
      const end = css.indexOf('*/', i + 2)
      if (end < 0) {
        out += css.slice(i)
        break
      }
      out += css.slice(i, end + 2)
      i = end + 2
      continue
    }
    if (c === '"' || c === "'") {
      const quote = c
      const start = i
      i++
      while (i < css.length && css.charAt(i) !== quote) {
        if (css.charAt(i) === '\\') i++
        i++
      }
      if (i < css.length) i++
      out += css.slice(start, i)
      continue
    }
    if (css.startsWith(GLOBAL_PREFIX, i)) {
      // Strip the wrapper — emit the inner body as-is. Nested classes are
      // intentionally left unscoped (that's what :global means).
      const innerStart = i + GLOBAL_PREFIX.length
      const wrapperEnd = skipGlobalInterior(css, i)
      out += css.slice(innerStart, wrapperEnd - 1) // exclude the trailing `)`
      i = wrapperEnd
      continue
    }
    if (c === '.' && i + 1 < css.length && isClassFirst(css.charAt(i + 1))) {
      const start = i
      i++ // skip dot
      while (i < css.length && isClassPart(css.charAt(i))) i++
      const name = css.slice(start + 1, i)
      out += '.' + name
      if (declared.has(name)) out += `-tu-${hash}`
      continue
    }
    out += c
    i++
  }
  return out
}

// ─── Hash ───────────────────────────────────────────────────────────────────

/** FNV-1a 32-bit, returned as the leading 6 hex digits. */
function fnv1a6(input: string): string {
  let h = 0x811c9dc5
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  return (h >>> 0).toString(16).padStart(8, '0').slice(0, 6)
}

// ─── Source map (V3) ───────────────────────────────────────────────────────

const VLQ_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

function encodeVLQ(n: number): string {
  let v = n < 0 ? ((-n) << 1) | 1 : n << 1
  let out = ''
  do {
    let digit = v & 0b11111
    v >>>= 5
    if (v > 0) digit |= 0b100000
    out += VLQ_CHARS.charAt(digit)
  } while (v > 0)
  return out
}

/**
 * Build a V3 source map from the per-statement and per-token mapping anchors.
 * Token mappings are folded in as additional segments (start position only —
 * V3 has no native end-of-segment representation; the LSP consumes the
 * richer `tokenMappings` list directly for diagnostic-range translation).
 */
function buildV3Map(
  stmtMappings: StmtMapping[],
  tokenMappings: TokenMapping[],
  generated: string,
  source: string,
  filename: string
): SourceMapV3 {
  const totalGenLines = generated === '' ? 0 : generated.split('\n').length
  // Group all mappings by generated line. Both stmt anchors and token spans
  // contribute one segment each (token spans use their start position).
  const byLine = new Map<number, { genCol: number; srcLine: number; srcCol: number }[]>()
  const push = (jsOffset: number, srcOffset: number) => {
    const gen = lineColAt(generated, jsOffset)
    const src = lineColAt(source, srcOffset)
    const list = byLine.get(gen.line - 1) ?? []
    list.push({ genCol: gen.col - 1, srcLine: src.line - 1, srcCol: src.col - 1 })
    byLine.set(gen.line - 1, list)
  }
  for (const m of stmtMappings) push(m.jsOffset, m.srcOffset)
  for (const t of tokenMappings) push(t.jsStart, t.srcStart)
  // VLQ-encode segments line-by-line. genCol resets each line; srcLine/srcCol
  // are relative across the whole map.
  const out: string[] = []
  let prevSrcLine = 0
  let prevSrcCol = 0
  for (let line = 0; line < totalGenLines; line++) {
    const segs = byLine.get(line) ?? []
    segs.sort((a, b) => a.genCol - b.genCol)
    let prevGenCol = 0
    const segStrs: string[] = []
    for (const seg of segs) {
      let s = ''
      s += encodeVLQ(seg.genCol - prevGenCol)
      s += encodeVLQ(0) // sources index (we only ever have one source)
      s += encodeVLQ(seg.srcLine - prevSrcLine)
      s += encodeVLQ(seg.srcCol - prevSrcCol)
      segStrs.push(s)
      prevGenCol = seg.genCol
      prevSrcLine = seg.srcLine
      prevSrcCol = seg.srcCol
    }
    out.push(segStrs.join(','))
  }
  return {
    version: 3,
    file: filename,
    sources: [filename],
    sourcesContent: [source],
    names: [],
    mappings: out.join(';'),
  }
}

/** Base64-encode a UTF-8 string. Works in Node (Buffer) and the browser (btoa). */
function base64Encode(s: string): string {
  if (typeof Buffer !== 'undefined') {
    return Buffer.from(s, 'utf8').toString('base64')
  }
  // Browser fallback — `btoa` only handles bytes in 0x00..0xFF, so we
  // funnel UTF-8 bytes through a Latin-1 string first.
  const bytes = new TextEncoder().encode(s)
  let bin = ''
  for (const b of bytes) bin += String.fromCharCode(b)
  return btoa(bin)
}
